// <auto-generated />
using System;
using DeveloperTools.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeveloperTools.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251129124816_FixColumnNames")]
    partial class FixColumnNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeveloperTools.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 13, DateTimeKind.Utc).AddTicks(9383),
                            Description = "JSON formatting, validation, and conversion tools",
                            DisplayOrder = 1,
                            Icon = "braces",
                            Name = "JSON Tools",
                            Slug = "json",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 13, DateTimeKind.Utc).AddTicks(9384)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(420),
                            Description = "Base64, URL encoding and decoding tools",
                            DisplayOrder = 2,
                            Icon = "code",
                            Name = "Encoding & Decoding",
                            Slug = "encoding",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(421)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(424),
                            Description = "UUID, password, QR code, and other generators",
                            DisplayOrder = 3,
                            Icon = "wand",
                            Name = "Generators",
                            Slug = "generators",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(424)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(426),
                            Description = "Hash generators and encryption tools",
                            DisplayOrder = 4,
                            Icon = "lock",
                            Name = "Cryptography",
                            Slug = "crypto",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(426)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(427),
                            Description = "Text manipulation and formatting tools",
                            DisplayOrder = 5,
                            Icon = "text",
                            Name = "Text Tools",
                            Slug = "text",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(428)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(438),
                            Description = "Data format converters",
                            DisplayOrder = 6,
                            Icon = "arrows",
                            Name = "Converters",
                            Slug = "converters",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(438)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(440),
                            Description = "SQL, CSS, JavaScript formatters",
                            DisplayOrder = 7,
                            Icon = "code",
                            Name = "Formatters",
                            Slug = "formatters",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(440)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(441),
                            Description = "Developer utilities and helpers",
                            DisplayOrder = 8,
                            Icon = "tool",
                            Name = "Utilities",
                            Slug = "utilities",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(441)
                        });
                });

            modelBuilder.Entity("DeveloperTools.Core.Entities.RelatedTool", b =>
                {
                    b.Property<int>("ToolId")
                        .HasColumnType("integer")
                        .HasColumnName("tool_id");

                    b.Property<int>("RelatedToolId")
                        .HasColumnType("integer")
                        .HasColumnName("related_tool_id");

                    b.Property<int>("RelevanceScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("relevance_score");

                    b.HasKey("ToolId", "RelatedToolId");

                    b.HasIndex("RelatedToolId");

                    b.ToTable("related_tools", (string)null);
                });

            modelBuilder.Entity("DeveloperTools.Core.Entities.SeoMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("canonical_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("meta_description");

                    b.Property<string>("OgDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("og_description");

                    b.Property<string>("OgImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("og_image_url");

                    b.Property<string>("OgTitle")
                        .HasMaxLength(95)
                        .HasColumnType("character varying(95)")
                        .HasColumnName("og_title");

                    b.Property<string>("StructuredData")
                        .HasColumnType("jsonb")
                        .HasColumnName("structured_data");

                    b.Property<string>("Title")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("title");

                    b.Property<int>("ToolId")
                        .HasColumnType("integer")
                        .HasColumnName("tool_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ToolId")
                        .IsUnique();

                    b.ToTable("seo_metadata", (string)null);
                });

            modelBuilder.Entity("DeveloperTools.Core.Entities.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.PrimitiveCollection<string[]>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("keywords");

                    b.Property<string>("LongDescription")
                        .HasColumnType("text")
                        .HasColumnName("long_description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("ProcessingType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("client")
                        .HasColumnName("processing_type");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("short_description");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("usage_count");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tools", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(5793),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = true,
                            Keywords = new[] { "json formatter", "json beautifier", "format json online", "json pretty print" },
                            LongDescription = "Free online JSON formatter and beautifier. Paste your JSON data and get formatted, indented output instantly.",
                            Name = "JSON Formatter",
                            ProcessingType = "client",
                            ShortDescription = "Format and beautify JSON data",
                            Slug = "json-formatter",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(5794),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7394),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = true,
                            Keywords = new[] { "base64 encoder", "base64 decoder", "base64 online", "encode base64" },
                            LongDescription = "Free online Base64 encoder and decoder. Convert text to Base64 and vice versa instantly.",
                            Name = "Base64 Encoder/Decoder",
                            ProcessingType = "client",
                            ShortDescription = "Encode or decode Base64 strings",
                            Slug = "base64",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7395),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7400),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsFeatured = true,
                            Keywords = new[] { "url encoder", "url decoder", "urlencode online", "percent encoding" },
                            LongDescription = "URL encode or decode your strings online. Perfect for working with query parameters and URLs.",
                            Name = "URL Encoder/Decoder",
                            ProcessingType = "client",
                            ShortDescription = "Encode or decode URL strings",
                            Slug = "url-encoder",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7400),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7403),
                            DisplayOrder = 3,
                            IsActive = true,
                            IsFeatured = true,
                            Keywords = new[] { "jwt decoder", "decode jwt", "jwt parser", "json web token decoder" },
                            LongDescription = "Decode JSON Web Tokens (JWT) and inspect their header, payload, and signature.",
                            Name = "JWT Decoder",
                            ProcessingType = "client",
                            ShortDescription = "Decode and inspect JWT tokens",
                            Slug = "jwt-decoder",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7403),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7405),
                            DisplayOrder = 4,
                            IsActive = true,
                            IsFeatured = false,
                            Keywords = new[] { "html entity encoder", "html entity decoder", "html encode", "special characters html" },
                            LongDescription = "Convert special characters to HTML entities or decode HTML entities back to characters.",
                            Name = "HTML Entity Encoder/Decoder",
                            ProcessingType = "client",
                            ShortDescription = "Encode or decode HTML entities",
                            Slug = "html-entity",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7406),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7433),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = true,
                            Keywords = new[] { "uuid generator", "guid generator", "random uuid", "uuid v4" },
                            LongDescription = "Generate random UUID v4 (GUID) values. Create single or bulk UUIDs instantly.",
                            Name = "UUID Generator",
                            ProcessingType = "client",
                            ShortDescription = "Generate random UUIDs/GUIDs",
                            Slug = "uuid-generator",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7434),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7436),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsFeatured = true,
                            Keywords = new[] { "password generator", "random password", "secure password generator", "strong password" },
                            LongDescription = "Generate strong, secure random passwords with customizable length and character sets.",
                            Name = "Password Generator",
                            ProcessingType = "client",
                            ShortDescription = "Generate secure random passwords",
                            Slug = "password-generator",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7436),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7438),
                            DisplayOrder = 3,
                            IsActive = true,
                            IsFeatured = false,
                            Keywords = new[] { "lorem ipsum generator", "placeholder text", "dummy text", "filler text" },
                            LongDescription = "Generate Lorem Ipsum placeholder text for designs and mockups.",
                            Name = "Lorem Ipsum Generator",
                            ProcessingType = "client",
                            ShortDescription = "Generate placeholder text",
                            Slug = "lorem-ipsum",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7439),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7441),
                            DisplayOrder = 4,
                            IsActive = true,
                            IsFeatured = true,
                            Keywords = new[] { "qr code generator", "create qr code", "qr code maker", "free qr code" },
                            LongDescription = "Generate QR codes for URLs, text, email, phone, WiFi, and more.",
                            Name = "QR Code Generator",
                            ProcessingType = "client",
                            ShortDescription = "Generate QR codes from text or URLs",
                            Slug = "qr-code",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7441),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7443),
                            DisplayOrder = 5,
                            IsActive = true,
                            IsFeatured = false,
                            Keywords = new[] { "slug generator", "url slug", "seo friendly url", "permalink generator" },
                            LongDescription = "Convert text to clean, SEO-friendly URL slugs with transliteration support.",
                            Name = "Slug Generator",
                            ProcessingType = "client",
                            ShortDescription = "Generate SEO-friendly URL slugs",
                            Slug = "slug-generator",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7443),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7445),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = true,
                            Keywords = new[] { "md5 generator", "md5 hash", "md5 online", "generate md5" },
                            LongDescription = "Generate MD5 hash values from any text input. Fast and free online MD5 generator.",
                            Name = "MD5 Hash Generator",
                            ProcessingType = "client",
                            ShortDescription = "Generate MD5 hash from text",
                            Slug = "md5-hash",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7445),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7447),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsFeatured = true,
                            Keywords = new[] { "sha256 generator", "sha256 hash", "sha256 online", "generate sha256" },
                            LongDescription = "Generate SHA256 hash values from any text input. Secure hashing algorithm.",
                            Name = "SHA256 Hash Generator",
                            ProcessingType = "client",
                            ShortDescription = "Generate SHA256 hash from text",
                            Slug = "sha256-hash",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7448),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7450),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = true,
                            Keywords = new[] { "regex tester", "regex online", "test regex", "regular expression tester" },
                            LongDescription = "Test your regular expressions in real-time. Supports JavaScript regex with match highlighting.",
                            Name = "Regex Tester",
                            ProcessingType = "client",
                            ShortDescription = "Test and debug regular expressions",
                            Slug = "regex-tester",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7450),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7452),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsFeatured = false,
                            Keywords = new[] { "text diff", "compare text", "diff checker", "text comparison" },
                            LongDescription = "Compare two texts side-by-side and visualize additions, deletions, and changes.",
                            Name = "Text Diff Tool",
                            ProcessingType = "client",
                            ShortDescription = "Compare two texts and find differences",
                            Slug = "text-diff",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7452),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7454),
                            DisplayOrder = 3,
                            IsActive = true,
                            IsFeatured = false,
                            Keywords = new[] { "markdown preview", "markdown editor", "markdown to html", "md preview" },
                            LongDescription = "Write Markdown and see the rendered output in real-time. Export to HTML.",
                            Name = "Markdown Preview",
                            ProcessingType = "client",
                            ShortDescription = "Preview Markdown in real-time",
                            Slug = "markdown-preview",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7454),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7456),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = true,
                            Keywords = new[] { "timestamp converter", "unix timestamp", "epoch converter", "date converter" },
                            LongDescription = "Convert Unix timestamps to human-readable dates and vice versa.",
                            Name = "Timestamp Converter",
                            ProcessingType = "client",
                            ShortDescription = "Convert Unix timestamps to dates",
                            Slug = "timestamp-converter",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7457),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7459),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsFeatured = true,
                            Keywords = new[] { "color converter", "hex to rgb", "rgb to hex", "hsl converter" },
                            LongDescription = "Convert colors between HEX, RGB, and HSL formats with color picker.",
                            Name = "Color Converter",
                            ProcessingType = "client",
                            ShortDescription = "Convert colors between formats",
                            Slug = "color-converter",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7459),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7461),
                            DisplayOrder = 3,
                            IsActive = true,
                            IsFeatured = false,
                            Keywords = new[] { "json to csv", "csv to json", "json converter", "csv converter" },
                            LongDescription = "Convert JSON arrays to CSV format or CSV data to JSON.",
                            Name = "JSON to CSV Converter",
                            ProcessingType = "client",
                            ShortDescription = "Convert JSON to CSV and vice versa",
                            Slug = "json-csv",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7461),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7463),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = true,
                            Keywords = new[] { "sql formatter", "format sql", "sql beautifier", "sql pretty print" },
                            LongDescription = "Beautify messy SQL queries with proper indentation and formatting.",
                            Name = "SQL Formatter",
                            ProcessingType = "client",
                            ShortDescription = "Format and beautify SQL queries",
                            Slug = "sql-formatter",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7464),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7467),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsFeatured = false,
                            Keywords = new[] { "css minifier", "minify css", "css compressor", "css optimizer" },
                            LongDescription = "Reduce CSS file size by removing comments, whitespace, and optimizing values.",
                            Name = "CSS Minifier",
                            ProcessingType = "client",
                            ShortDescription = "Minify CSS code for production",
                            Slug = "css-minifier",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7467),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7469),
                            DisplayOrder = 3,
                            IsActive = true,
                            IsFeatured = false,
                            Keywords = new[] { "js minifier", "javascript minifier", "minify js", "javascript compressor" },
                            LongDescription = "Reduce JS file size by removing comments, whitespace, and console.log statements.",
                            Name = "JavaScript Minifier",
                            ProcessingType = "client",
                            ShortDescription = "Minify JavaScript code",
                            Slug = "js-minifier",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7469),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7471),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = true,
                            Keywords = new[] { "cron parser", "cron expression", "cron schedule", "crontab helper" },
                            LongDescription = "Understand what your cron job schedule means in plain English and see next execution times.",
                            Name = "Cron Expression Parser",
                            ProcessingType = "client",
                            ShortDescription = "Parse and explain cron expressions",
                            Slug = "cron-parser",
                            UpdatedAt = new DateTime(2025, 11, 29, 12, 48, 16, 14, DateTimeKind.Utc).AddTicks(7472),
                            UsageCount = 0
                        });
                });

            modelBuilder.Entity("DeveloperTools.Core.Entities.ToolFaq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<int>("ToolId")
                        .HasColumnType("integer")
                        .HasColumnName("tool_id");

                    b.HasKey("Id");

                    b.HasIndex("ToolId");

                    b.ToTable("tool_faqs", (string)null);
                });

            modelBuilder.Entity("DeveloperTools.Core.Entities.ToolUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("page_url");

                    b.Property<string>("Referrer")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("referrer");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("session_id");

                    b.Property<int?>("ToolId")
                        .HasColumnType("integer")
                        .HasColumnName("tool_id");

                    b.Property<string>("ToolSlug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("tool_slug");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_tool_usage_created_at");

                    b.HasIndex("ToolId");

                    b.HasIndex("ToolSlug", "CreatedAt")
                        .HasDatabaseName("idx_tool_usage_slug_date");

                    b.ToTable("tool_usage", (string)null);
                });

            modelBuilder.Entity("DeveloperTools.Core.Entities.RelatedTool", b =>
                {
                    b.HasOne("DeveloperTools.Core.Entities.Tool", "Related")
                        .WithMany()
                        .HasForeignKey("RelatedToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeveloperTools.Core.Entities.Tool", "Tool")
                        .WithMany("RelatedTools")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Related");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("DeveloperTools.Core.Entities.SeoMetadata", b =>
                {
                    b.HasOne("DeveloperTools.Core.Entities.Tool", "Tool")
                        .WithOne("SeoMetadata")
                        .HasForeignKey("DeveloperTools.Core.Entities.SeoMetadata", "ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("DeveloperTools.Core.Entities.Tool", b =>
                {
                    b.HasOne("DeveloperTools.Core.Entities.Category", "Category")
                        .WithMany("Tools")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DeveloperTools.Core.Entities.ToolFaq", b =>
                {
                    b.HasOne("DeveloperTools.Core.Entities.Tool", "Tool")
                        .WithMany("Faqs")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("DeveloperTools.Core.Entities.ToolUsage", b =>
                {
                    b.HasOne("DeveloperTools.Core.Entities.Tool", "Tool")
                        .WithMany("Usages")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("DeveloperTools.Core.Entities.Category", b =>
                {
                    b.Navigation("Tools");
                });

            modelBuilder.Entity("DeveloperTools.Core.Entities.Tool", b =>
                {
                    b.Navigation("Faqs");

                    b.Navigation("RelatedTools");

                    b.Navigation("SeoMetadata");

                    b.Navigation("Usages");
                });
#pragma warning restore 612, 618
        }
    }
}
