export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string;
  icon?: string;
  toolCount: number;
}

export interface Tool {
  id: number;
  name: string;
  slug: string;
  shortDescription?: string;
  categorySlug: string;
  categoryName: string;
  isFeatured: boolean;
}

export interface ToolDetail extends Tool {
  longDescription?: string;
  keywords: string[];
  seo?: {
    title?: string;
    metaDescription?: string;
    ogTitle?: string;
    ogDescription?: string;
    ogImageUrl?: string;
    canonicalUrl?: string;
    structuredData?: string;
  };
  faqs: { question: string; answer: string }[];
  relatedTools?: Tool[];
}

// Static data now that the backend is disabled.
export const categoryCatalog = [
  {
    id: 1,
    slug: 'json',
    name: 'JSON Tools',
    description:
      'JSON formatting, validation, querying, patching, size analysis, and conversion tools for developers',
    toolCount: 12,
  },
  {
    id: 2,
    slug: 'encoding',
    name: 'Encoder Online',
    description:
      'Encode and decode Base64, Base32, Hex, URL components, binary, images, and JSON strings',
    toolCount: 14,
  },
  {
    id: 3,
    slug: 'generators',
    name: 'Generators',
    description: 'UUID, ULID, color palettes, MAC address, password, mock data, ASCII art, and icons',
    toolCount: 43,
  },
  {
    id: 4,
    slug: 'crypto',
    name: 'Cryptography',
    description: 'JWT generator, password entropy, hashing, HMAC, certificates, htpasswd, and 2FA',
    toolCount: 24,
  },
  {
    id: 5,
    slug: 'text',
    name: 'Text Tools',
    description: 'UTF-8 byte counter, slug case converter, invisible character cleaner, and text tools',
    toolCount: 14,
  },
  {
    id: 6,
    slug: 'converters',
    name: 'Converters',
    description: 'Data format, HTML to JSX, SQL INSERT, GraphQL, TSV, NDJSON, Punycode, Morse, and converters',
    toolCount: 62,
  },
  {
    id: 7,
    slug: 'formatters',
    name: 'Code Formatters',
    description: 'Format and minify SQL, JSON, HTML, CSS, JS, and SVGs in various languages',
    toolCount: 15,
  },
  {
    id: 8,
    slug: 'utilities',
    name: 'Developer Utilities',
    description: 'Clip-path, scrollbar, patterns, SVG path, SemVer, IPv6, crontab, DNS, and utilities',
    toolCount: 67,
  },
] as const satisfies readonly Category[];

export type CategorySlug = (typeof categoryCatalog)[number]['slug'];

export const toolCatalog = [
  {
    id: 1,
    slug: 'json-formatter',
    name: 'JSON Formatter',
    shortDescription: 'Format and beautify JSON data',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 2,
    slug: 'json-validator',
    name: 'JSON Validator',
    shortDescription: 'Validate JSON syntax and structure',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 3,
    slug: 'json-csv',
    name: 'JSON to CSV',
    shortDescription: 'Convert JSON arrays to CSV and back',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 4,
    slug: 'json-to-typescript',
    name: 'JSON to TypeScript',
    shortDescription: 'Generate TypeScript interfaces from JSON',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 5,
    slug: 'base64',
    name: 'Base64 Encoder/Decoder',
    shortDescription: 'Encode or decode Base64 strings',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 6,
    slug: 'url-encoder',
    name: 'URL Encoder/Decoder',
    shortDescription: 'Encode or decode URL strings',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 7,
    slug: 'jwt-decoder',
    name: 'JWT Decoder, Signer & Verifier',
    shortDescription: 'Decode JWTs and sign or verify HS256, HS384, and HS512 tokens locally',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 8,
    slug: 'html-entity',
    name: 'HTML Entity Encoder/Decoder',
    shortDescription: 'Encode or decode HTML entities',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 9,
    slug: 'uuid-generator',
    name: 'UUID v4 & v7 Generator',
    shortDescription: 'Generate random v4 or timestamp-based v7 UUIDs',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 10,
    slug: 'password-generator',
    name: 'Password Generator',
    shortDescription: 'Create strong random passwords',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 11,
    slug: 'qr-code',
    name: 'QR Code Generator',
    shortDescription: 'Create QR codes from text or URLs',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 12,
    slug: 'slug-generator',
    name: 'Slug Generator',
    shortDescription: 'Generate clean URL slugs',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 13,
    slug: 'css-gradient',
    name: 'CSS Gradient',
    shortDescription: 'Design and export CSS gradients',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 14,
    slug: 'meta-tags',
    name: 'Meta Tags Generator',
    shortDescription: 'Generate SEO meta tags',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 15,
    slug: 'md5-hash',
    name: 'MD5 Hash',
    shortDescription: 'Generate MD5 hashes',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 16,
    slug: 'sha256-hash',
    name: 'SHA256 Hash',
    shortDescription: 'Generate SHA256 hashes',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 17,
    slug: 'regex-tester',
    name: 'Regex Tester',
    shortDescription: 'Test and debug regex patterns',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 18,
    slug: 'text-diff',
    name: 'Text Diff',
    shortDescription: 'Compare texts and highlight differences',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 19,
    slug: 'markdown-preview',
    name: 'Markdown Preview',
    shortDescription: 'Preview and convert Markdown to HTML',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 20,
    slug: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    shortDescription: 'Generate placeholder text',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 21,
    slug: 'timestamp-converter',
    name: 'Timestamp Converter',
    shortDescription: 'Convert timestamps to readable dates',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 22,
    slug: 'color-converter',
    name: 'Color Converter',
    shortDescription: 'Convert between HEX, RGB, and HSL',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 23,
    slug: 'image-to-base64',
    name: 'Image to Base64',
    shortDescription: 'Convert images to Base64',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 24,
    slug: 'yaml-json',
    name: 'YAML to JSON',
    shortDescription: 'Convert YAML to JSON and back',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 25,
    slug: 'sql-formatter',
    name: 'SQL Formatter',
    shortDescription: 'Format SQL queries',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 26,
    slug: 'css-minifier',
    name: 'CSS Minifier',
    shortDescription: 'Minify CSS for production',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 27,
    slug: 'js-minifier',
    name: 'JS Minifier',
    shortDescription: 'Minify JavaScript for production',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 28,
    slug: 'cron-parser',
    name: 'Cron Parser',
    shortDescription: 'Parse and explain cron expressions',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 29,
    slug: 'case-converter',
    name: 'Case Converter',
    shortDescription: 'Convert text between different cases',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 30,
    slug: 'word-counter',
    name: 'Word Counter',
    shortDescription: 'Count words, characters, lines, and sentences',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 31,
    slug: 'remove-duplicates',
    name: 'Remove Duplicate Lines',
    shortDescription: 'Remove duplicate lines from text',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 32,
    slug: 'sort-lines',
    name: 'Sort Lines',
    shortDescription: 'Sort lines alphabetically',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 33,
    slug: 'hex-encoder',
    name: 'HEX Encoder/Decoder',
    shortDescription: 'Encode or decode text to or from hexadecimal',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 34,
    slug: 'binary-encoder',
    name: 'Binary Encoder/Decoder',
    shortDescription: 'Encode or decode text to or from binary',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 35,
    slug: 'html-formatter',
    name: 'HTML Formatter',
    shortDescription: 'Format and beautify HTML code',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 36,
    slug: 'html-minifier',
    name: 'HTML Minifier',
    shortDescription: 'Minify HTML code for production',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 37,
    slug: 'xml-formatter',
    name: 'XML Formatter',
    shortDescription: 'Format and beautify XML code',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 38,
    slug: 'sha512-hash',
    name: 'SHA512 Hash Generator',
    shortDescription: 'Generate SHA512 hashes from text',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 39,
    slug: 'roman-numeral-converter',
    name: 'Roman Numeral Converter',
    shortDescription: 'Convert numbers to and from Roman numerals',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 40,
    slug: 'number-base-converter',
    name: 'Number Base Converter',
    shortDescription: 'Convert between decimal, hexadecimal, octal, and binary',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 41,
    slug: 'unicode-escape',
    name: 'Unicode Escape Encoder/Decoder',
    shortDescription: 'Convert text to and from Unicode escape sequences',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 42,
    slug: 'json-string-escape',
    name: 'JSON String Escape',
    shortDescription: 'Escape and unescape JSON string content',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 43,
    slug: 'regex-escape',
    name: 'Regex Escape',
    shortDescription: 'Escape text for safe use in regular expressions',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 44,
    slug: 'url-parser',
    name: 'URL Parser',
    shortDescription: 'Parse URLs into protocol, host, path, and query parameters',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 45,
    slug: 'query-string-parser',
    name: 'Query String Parser',
    shortDescription: 'Parse and build URL query strings',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 46,
    slug: 'http-headers-parser',
    name: 'HTTP Headers Parser',
    shortDescription: 'Convert raw HTTP headers to JSON and back',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 47,
    slug: 'http-status-codes',
    name: 'HTTP Status Codes',
    shortDescription: 'Search and reference common HTTP status codes',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 48,
    slug: 'user-agent-parser',
    name: 'User Agent Parser Online',
    shortDescription:
      'Parse browser, OS, engine, device, CPU, and bot fields from one or many User-Agent strings',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 49,
    slug: 'json-schema-validator',
    name: 'JSON Schema Validator',
    shortDescription: 'Validate JSON documents against JSON Schema rules',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 50,
    slug: 'hmac-generator',
    name: 'HMAC Generator & Verifier',
    shortDescription: 'Generate and verify keyed SHA message authentication codes',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 51,
    slug: 'pkce-generator',
    name: 'PKCE Generator & Verifier',
    shortDescription: 'Generate and verify OAuth PKCE S256 verifier and challenge pairs',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 52,
    slug: 'cidr-calculator',
    name: 'IPv4 CIDR Calculator',
    shortDescription: 'Calculate IPv4 network ranges, masks, broadcasts, and usable hosts',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 53,
    slug: 'json-pointer',
    name: 'JSON Pointer Evaluator',
    shortDescription: 'Resolve RFC 6901 JSON Pointer paths against JSON documents',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 54,
    slug: 'chmod-calculator',
    name: 'Chmod Calculator',
    shortDescription: 'Convert Unix file permissions between octal and symbolic modes',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 55,
    slug: 'cache-control',
    name: 'Cache-Control Parser & Builder',
    shortDescription: 'Parse, normalize, and check HTTP Cache-Control directives',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 56,
    slug: 'jsonpath-tester',
    name: 'JSONPath Tester',
    shortDescription:
      'Query JSON with RFC 9535-style paths, wildcards, slices, and recursive descent',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 57,
    slug: 'csp-builder',
    name: 'CSP Header Builder & Analyzer',
    shortDescription: 'Build, normalize, and inspect Content Security Policy headers',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 58,
    slug: 'curl-to-fetch',
    name: 'cURL Builder & Fetch Converter',
    shortDescription: 'Build cURL requests or convert safe cURL input to JavaScript fetch',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 59,
    slug: 'env-to-json',
    name: '.env to JSON Converter',
    shortDescription: 'Convert dotenv variables to JSON and back without uploading secrets',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 60,
    slug: 'json-to-zod',
    name: 'JSON to Zod Schema',
    shortDescription: 'Generate Zod schemas and inferred TypeScript types from JSON samples',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 61,
    slug: 'bcrypt-generator',
    name: 'Bcrypt Generator & Verifier',
    shortDescription: 'Generate salted bcrypt hashes and verify test passwords locally',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 62,
    slug: 'json-diff-patch',
    name: 'JSON Diff & Patch Generator',
    shortDescription: 'Generate and apply RFC 6902 JSON Patch operations locally',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 63,
    slug: 'color-contrast-checker',
    name: 'Color Contrast Checker',
    shortDescription: 'Check WCAG text and UI contrast ratios with a live preview',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 64,
    slug: 'certificate-decoder',
    name: 'PEM / X.509 Certificate Decoder',
    shortDescription:
      'Inspect certificate identities, validity, SANs, algorithms, and fingerprints locally',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 65,
    slug: 'openapi-validator',
    name: 'OpenAPI Validator & Endpoint Explorer',
    shortDescription: 'Validate OpenAPI 3 documents and explore endpoint operations locally',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 66,
    slug: 'svg-to-jsx',
    name: 'SVG to JSX / React Converter',
    shortDescription: 'Convert SVG markup to React JSX/TSX components with custom options',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 67,
    slug: 'svg-minifier',
    name: 'SVG Optimizer & Minifier',
    shortDescription: 'Optimize and shrink SVG file sizes with live rendered preview',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 68,
    slug: 'css-clamp',
    name: 'CSS clamp() Fluid Calculator',
    shortDescription: 'Calculate fluid responsive typography and spacing CSS clamp() values',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 69,
    slug: 'css-box-shadow',
    name: 'CSS Box Shadow Generator',
    shortDescription: 'Create multi-layer box shadows and glassmorphism styling visually',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 70,
    slug: 'docker-run-to-compose',
    name: 'Docker Run to Compose Converter',
    shortDescription: 'Convert docker run commands into docker-compose.yml services',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 71,
    slug: 'cron-generator',
    name: 'Visual Cron Expression Builder',
    shortDescription: 'Build standard cron expressions visually with schedule preview',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 72,
    slug: 'json-to-sql',
    name: 'JSON to SQL Converter',
    shortDescription: 'Generate SQL INSERT queries and CREATE TABLE DDL from JSON data',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 73,
    slug: 'bip39-generator',
    name: 'BIP-39 Mnemonic Generator',
    shortDescription: 'Generate and validate 12/24-word cryptocurrency mnemonic seed phrases',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 74,
    slug: 'dmarc-generator',
    name: 'DMARC & SPF Record Generator',
    shortDescription: 'Generate SPF, DMARC, and DKIM DNS TXT records for domain email security',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 75,
    slug: 'json-to-models',
    name: 'JSON to Multi-Language Models',
    shortDescription: 'Generate Go structs, Python Pydantic, Rust Serde, and C# from JSON',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 76,
    slug: 'px-to-rem',
    name: 'PX to REM & EM Converter',
    shortDescription: 'Convert pixel dimensions to REM, EM, VW, VH, and CSS units',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 77,
    slug: 'mock-data-generator',
    name: 'Mock Data JSON Generator',
    shortDescription: 'Generate realistic mock JSON datasets for users, products, and orders',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 78,
    slug: 'csv-to-markdown',
    name: 'CSV to Markdown Table Converter',
    shortDescription: 'Convert CSV and TSV spreadsheets to GitHub-flavored Markdown tables',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 79,
    slug: 'curl-to-code',
    name: 'cURL to Multi-Language Code',
    shortDescription: 'Convert cURL commands to JavaScript Fetch, Axios, Python, Go, PHP, and Rust',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 80,
    slug: 'rsa-key-pair-generator',
    name: 'RSA & ECDSA Key Pair Generator',
    shortDescription: 'Generate RSA and ECDSA public/private key pairs in PEM format securely in browser',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 81,
    slug: 'svg-optimizer',
    name: 'SVG Optimizer & Cleaner',
    shortDescription: 'Minify SVG code, remove editor metadata, clean paths, and inspect byte savings',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 82,
    slug: 'html-table-to-json',
    name: 'HTML Table to JSON Converter',
    shortDescription: 'Extract and parse HTML table markup into structured JSON objects or arrays',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 83,
    slug: 'favicon-generator',
    name: 'Favicon & App Icon Generator',
    shortDescription: 'Generate 16x16, 32x32, Apple Touch icons, web manifest, and HTML link tags',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 84,
    slug: 'gitignore-generator',
    name: '.gitignore Generator',
    shortDescription: 'Generate customized .gitignore files for Node, Python, Java, Go, Rust, macOS, and IDEs',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 85,
    slug: 'htpasswd-generator',
    name: '.htpasswd Generator',
    shortDescription: 'Generate Bcrypt, MD5, and SHA-1 password hashes for Apache and Nginx HTTP Basic Auth',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 86,
    slug: 'dockerfile-generator',
    name: 'Dockerfile Generator',
    shortDescription: 'Generate production-ready multi-stage Dockerfiles for Node, Python, Go, Rust, and Nginx',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 87,
    slug: 'css-glassmorphism',
    name: 'CSS Glassmorphism Generator',
    shortDescription: 'Design modern frosted glass UI cards with real-time blur, opacity, and Tailwind CSS',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 88,
    slug: 'css-grid-generator',
    name: 'CSS Grid Layout Generator',
    shortDescription: 'Create custom CSS Grid layouts with column/row spans, gaps, and interactive preview',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 89,
    slug: 'css-blob-generator',
    name: 'CSS & SVG Blob Generator',
    shortDescription: 'Generate smooth organic blob shapes using fancy CSS border-radius and SVG paths',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 90,
    slug: 'robots-txt-generator',
    name: 'robots.txt Generator & Tester',
    shortDescription: 'Create SEO-optimized robots.txt files with custom user-agents, disallow rules, and sitemaps',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 91,
    slug: 'sitemap-generator',
    name: 'XML Sitemap Generator',
    shortDescription: 'Generate valid sitemap.xml files with lastmod, changefreq, and priority tags from URL lists',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 92,
    slug: 'sql-to-json',
    name: 'SQL to JSON Converter',
    shortDescription: 'Convert SQL INSERT statements and table dumps into structured JSON arrays and objects',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 93,
    slug: 'totp-generator',
    name: '2FA / TOTP Authenticator Generator',
    shortDescription: 'Generate RFC 6238 TOTP security codes, base32 secrets, and otpauth:// QR URIs',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 94,
    slug: 'markdown-table-generator',
    name: 'Markdown Table Generator',
    shortDescription: 'Create, edit, and format GitHub Markdown tables with an interactive spreadsheet editor',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 95,
    slug: 'key-code-info',
    name: 'JavaScript Keycode Info',
    shortDescription: 'Inspect keyboard event.key, code, which, and keyCode values with live keypress listener',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 96,
    slug: 'aspect-ratio-calculator',
    name: 'Aspect Ratio Calculator',
    shortDescription: 'Calculate 16:9, 4:3, 21:9 image and video aspect ratios with proportional resizing',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 97,
    slug: 'base64-to-image',
    name: 'Base64 to Image Decoder',
    shortDescription: 'Decode Base64 strings and Data URIs back into PNG, JPG, WebP, and SVG image files',
    categorySlug: 'encoding',
    categoryName: 'Encoder Online',
    isFeatured: true,
  },
  {
    id: 98,
    slug: 'html-to-markdown',
    name: 'HTML to Markdown Converter',
    shortDescription: 'Convert HTML markup, headings, links, blockquotes, and lists into clean Markdown',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 99,
    slug: 'css-triangle-generator',
    name: 'CSS Triangle Generator',
    shortDescription: 'Generate pure CSS border triangles and tooltips pointing in any direction',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 100,
    slug: 'svg-placeholder-generator',
    name: 'SVG Placeholder Generator',
    shortDescription: 'Generate custom SVG and Data URI image placeholders with dimensions and custom text',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 101,
    slug: 'css-flexbox-generator',
    name: 'CSS Flexbox Generator',
    shortDescription: 'Visual interactive CSS flexbox container and items playground with code export',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 102,
    slug: 'open-graph-previewer',
    name: 'Open Graph & Social Previewer',
    shortDescription: 'Preview Twitter, Facebook, LinkedIn, Discord, and Google SERP social share cards',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 103,
    slug: 'ascii-art-generator',
    name: 'ASCII Art & Banner Generator',
    shortDescription: 'Generate large ASCII font art banners for code comments, READMEs, and terminals',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 104,
    slug: 'css-animation-generator',
    name: 'CSS Animation Generator',
    shortDescription: 'Generate CSS keyframe animations (bounce, pulse, shake, spin, flip) with live preview',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 105,
    slug: 'markdown-to-html',
    name: 'Markdown to HTML Converter',
    shortDescription: 'Convert Markdown syntax to formatted and minified raw HTML markup',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 106,
    slug: 'css-text-shadow',
    name: 'CSS Text Shadow Generator',
    shortDescription: 'Generate multi-layer text shadows, 3D typography, and neon glow CSS effects',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 107,
    slug: 'time-duration-calculator',
    name: 'Time Duration & Date Diff',
    shortDescription: 'Calculate exact elapsed time between two dates and convert between time units',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 108,
    slug: 'xml-to-json',
    name: 'XML to JSON & JSON to XML',
    shortDescription: 'Convert XML data to structured JSON and JSON objects to valid XML markup',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 109,
    slug: 'list-to-sql-in',
    name: 'List to SQL IN Clause',
    shortDescription: 'Convert text lists, column IDs, and spreadsheets to formatted SQL IN clauses',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 110,
    slug: 'svg-to-png',
    name: 'SVG to PNG / JPG / WebP Converter',
    shortDescription: 'Convert vector SVG graphics into high-resolution raster images (PNG, JPEG, WebP)',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 111,
    slug: 'ip-subnet-calculator',
    name: 'IPv4 Subnet Calculator',
    shortDescription: 'Calculate network address, broadcast, usable host IP range, subnet mask, and CIDR',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 112,
    slug: 'css-filter-generator',
    name: 'CSS Filter Generator',
    shortDescription: 'Generate CSS image filters (blur, brightness, contrast, grayscale, hue, sepia)',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 113,
    slug: 'bcrypt-verifier',
    name: 'Bcrypt Hash Verifier',
    shortDescription: 'Verify plain text passwords against Bcrypt hashes and inspect cost and salt rounds',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 114,
    slug: 'css-border-radius',
    name: 'CSS 8-Point Border Radius',
    shortDescription: 'Generate advanced 8-point asymmetric border-radius, organic blobs, and squircles',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 115,
    slug: 'jwt-generator',
    name: 'JWT Token Generator',
    shortDescription: 'Create and sign custom JWT tokens with HMAC-SHA256, expiration, and payload claims',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 116,
    slug: 'ulid-generator',
    name: 'ULID & UUID v7 Generator',
    shortDescription: 'Generate timestamp-ordered sortable 128-bit ULIDs and UUID v7 identifiers',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 117,
    slug: 'curl-builder',
    name: 'cURL Command Builder',
    shortDescription: 'Visual API request client to construct and export executable terminal cURL commands',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 118,
    slug: 'base64-to-pdf',
    name: 'Base64 to PDF Converter',
    shortDescription: 'Decode Base64 strings directly into an in-browser PDF document viewer with download',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 119,
    slug: 'css-neumorphism',
    name: 'CSS Neumorphism Generator',
    shortDescription: 'Generate soft UI neumorphic shadows, inset depth, and convex shapes with pure CSS',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 120,
    slug: 'string-byte-counter',
    name: 'String Byte & UTF-8 Counter',
    shortDescription: 'Calculate UTF-8 byte length, character count, and database VARCHAR column limits',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 121,
    slug: 'css-mesh-gradient',
    name: 'CSS Mesh Gradient Generator',
    shortDescription: 'Generate modern multi-point mesh and aura radial gradients for UI hero backgrounds',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 122,
    slug: 'html-to-jsx',
    name: 'HTML to JSX / React Converter',
    shortDescription: 'Convert HTML markup into React JSX components with camelCase attributes and inline styles',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 123,
    slug: 'css-clip-path',
    name: 'CSS Clip-Path & Polygon Generator',
    shortDescription: 'Design visual clip-path polygons, geometric shapes, and custom masks with pure CSS',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 124,
    slug: 'css-scrollbar-generator',
    name: 'Custom CSS Scrollbar Generator',
    shortDescription: 'Generate custom scrollbar styles with WebKit pseudo-elements and standard scrollbar-color',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 125,
    slug: 'css-pattern-generator',
    name: 'CSS Background Pattern Generator',
    shortDescription: 'Create pure CSS repeating background patterns including dot grids, stripes, and blueprints',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 126,
    slug: 'svg-path-visualizer',
    name: 'SVG Path Visualizer & Inspector',
    shortDescription: 'Visualize, inspect, and analyze SVG path d-attribute commands and coordinates',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 127,
    slug: 'color-palette-generator',
    name: 'Tailwind Color Palette Generator',
    shortDescription: 'Generate accessible 50-950 color shade scales and harmony palettes from any hex color',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 128,
    slug: 'csv-to-sql-insert',
    name: 'CSV to SQL INSERT Generator',
    shortDescription: 'Convert CSV spreadsheets into batch SQL INSERT statements for PostgreSQL, MySQL, and SQLite',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 129,
    slug: 'sql-minifier',
    name: 'SQL Query Minifier',
    shortDescription: 'Strip comments and whitespace to compress SQL queries into compact single-line statements',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 130,
    slug: 'json-to-graphql',
    name: 'JSON to GraphQL Schema Generator',
    shortDescription: 'Infer GraphQL types, inputs, and schemas automatically from sample JSON payloads',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 131,
    slug: 'tsv-to-json',
    name: 'TSV to JSON Converter',
    shortDescription: 'Convert tab-separated values (TSV) into structured JSON arrays and back',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 132,
    slug: 'ndjson-to-json',
    name: 'NDJSON / JSONL to JSON Converter',
    shortDescription: 'Convert newline-delimited JSON log streams into standard JSON arrays and back',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 133,
    slug: 'json-size-analyzer',
    name: 'JSON Size & Memory Analyzer',
    shortDescription: 'Analyze JSON byte size, nesting depth, object distribution, and minification savings',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 134,
    slug: 'hex-to-base64',
    name: 'Hex to Base64 Converter',
    shortDescription: 'Convert raw hexadecimal byte strings into Base64 encoding and vice versa',
    categorySlug: 'encoding',
    categoryName: 'Encoder Online',
    isFeatured: true,
  },
  {
    id: 135,
    slug: 'punycode-converter',
    name: 'Punycode & IDN Domain Converter',
    shortDescription: 'Convert international domain names (IDNs) between Unicode and ASCII Punycode (xn--)',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 136,
    slug: 'morse-code-converter',
    name: 'Morse Code Audio & Text Translator',
    shortDescription: 'Translate plain text to Morse code with real-time audio playback and decode back',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 137,
    slug: 'base32-encoder',
    name: 'Base32 Encoder & Decoder',
    shortDescription: 'Encode and decode strings to RFC 4648 Base32 format for 2FA seeds and tokens',
    categorySlug: 'encoding',
    categoryName: 'Encoder Online',
    isFeatured: true,
  },
  {
    id: 138,
    slug: 'password-strength-analyzer',
    name: 'Password Strength & Entropy Analyzer',
    shortDescription: 'Calculate password entropy bits, brute-force crack time estimates, and complexity scores',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 139,
    slug: 'semver-calculator',
    name: 'Semver Range & Version Calculator',
    shortDescription: 'Evaluate semantic versioning ranges, check npm satisfies constraints, and bump releases',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 140,
    slug: 'ipv6-subnet-calculator',
    name: 'IPv6 Subnet & Prefix Calculator',
    shortDescription: 'Expand, compress, and calculate IPv6 prefix ranges, CIDR subnets, and address types',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 141,
    slug: 'mac-address-generator',
    name: 'MAC Address Generator & Formatter',
    shortDescription: 'Generate random unicast/multicast MAC addresses with colon, hyphen, or Cisco notation',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 142,
    slug: 'crontab-descriptor',
    name: 'Crontab Expression Explainer',
    shortDescription: 'Translate cron schedule expressions into natural human-readable English descriptions',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 143,
    slug: 'htaccess-to-nginx',
    name: 'Apache .htaccess to Nginx Converter',
    shortDescription: 'Convert Apache mod_rewrite rules, redirects, and headers into Nginx server blocks',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 144,
    slug: 'dns-record-generator',
    name: 'DNS Email Security Record Builder',
    shortDescription: 'Generate SPF, DKIM, and DMARC TXT records for email domain authentication',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 145,
    slug: 'slug-to-title',
    name: 'Slug to Title & Case Converter',
    shortDescription: 'Convert URL slugs into Title Case headlines, Sentence case, PascalCase, and camelCase',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 146,
    slug: 'text-obfuscator',
    name: 'Invisible Character & Zero-Width Detector',
    shortDescription: 'Detect and remove hidden zero-width spaces, Unicode marks, and invisible formatting',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 147,
    slug: 'csv-column-extractor',
    name: 'CSV Column Extractor & Filter',
    shortDescription: 'Select, extract, and reorder specific columns from large CSV data files',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 148,
    slug: 'sql-to-typescript',
    name: 'SQL Table to TypeScript Interface',
    shortDescription: 'Convert SQL CREATE TABLE schema definitions into type-safe TypeScript interfaces',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 149,
    slug: 'json-to-env',
    name: 'JSON to .env Converter',
    shortDescription: 'Flatten nested JSON objects into key-value environment variables and vice versa',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 150,
    slug: 'json-minifier',
    name: 'JSON Minifier & Stringifier',
    shortDescription: 'Minify JSON files by stripping whitespace to reduce API payload bandwidth',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 151,
    slug: 'markdown-table-to-csv',
    name: 'Markdown Table to CSV Converter',
    shortDescription: 'Convert GitHub markdown tables into spreadsheet-ready CSV files and Excel downloads',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 152,
    slug: 'llm-token-counter',
    name: 'LLM Token & Cost Calculator',
    shortDescription: 'Estimate token counts and API inference costs for GPT-4o, Claude 3.5, Gemini, and Llama 3 models.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 153,
    slug: 'openai-function-schema',
    name: 'OpenAI Function Calling Schema Generator',
    shortDescription: 'Convert JSON objects into structured OpenAI tool and function calling parameter schemas.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 154,
    slug: 'prompt-template-formatter',
    name: 'Prompt Template Compiler & Interpolator',
    shortDescription: 'Interpolate variables and validate placeholders in Jinja2 and Mustache AI prompt templates.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 155,
    slug: 'embedding-similarity',
    name: 'Embedding Vector Similarity Calculator',
    shortDescription: 'Calculate Cosine Similarity, Euclidean Distance, and Dot Product between embedding vectors.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 156,
    slug: 'text-chunk-splitter',
    name: 'RAG Text Chunk Splitter & Token Window Simulator',
    shortDescription: 'Split documents into overlapping token or character chunks for RAG vector search pipelines.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 157,
    slug: 'jsonl-dataset-validator',
    name: 'OpenAI JSONL Fine-Tuning Validator',
    shortDescription: 'Validate JSONL dataset files and message structures for OpenAI and Gemini model fine-tuning.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 158,
    slug: 'prompt-format-converter',
    name: 'ChatML, Anthropic & Llama 3 Prompt Converter',
    shortDescription: 'Convert chat prompts between ChatML, Anthropic Human/Assistant, and Llama 3 template formats.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 159,
    slug: 'sampling-curve-visualizer',
    name: 'LLM Temperature & Top-P Sampling Curve Visualizer',
    shortDescription: 'Simulate and visualize token probability distributions under temperature, Top-P, and Top-K sampling.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 160,
    slug: 'system-prompt-formatter',
    name: 'AI System Prompt Builder & Markdown Formatter',
    shortDescription: 'Format and structure AI system instructions with roles, guidelines, output formats, and examples.',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 161,
    slug: 'prompt-diff',
    name: 'AI Prompt Version & Semantic Diff Comparator',
    shortDescription: 'Compare two prompt revisions to highlight line changes, word additions, and token deltas.',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 162,
    slug: 'css-to-tailwind',
    name: 'CSS to Tailwind CSS Converter',
    shortDescription: 'Convert standard CSS rules and declaration blocks into Tailwind CSS utility classes.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 163,
    slug: 'tailwind-to-css',
    name: 'Tailwind to Vanilla CSS Converter',
    shortDescription: 'Convert Tailwind CSS classes back into standard, reusable vanilla CSS stylesheets.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 164,
    slug: 'css-specificity-calculator',
    name: 'CSS Specificity Calculator & Inspector',
    shortDescription: 'Calculate selector specificity tuples (IDs, classes, elements) and compare cascade overrides.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 165,
    slug: 'css-keyframes-generator',
    name: 'CSS Keyframe Animation Timeline Generator',
    shortDescription: 'Generate multi-step CSS @keyframes animations and timing rules with real-time visual preview.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 166,
    slug: 'tailwind-class-sorter',
    name: 'Tailwind Class Sorter & Formatter',
    shortDescription: 'Sort and deduplicate Tailwind CSS classes following the official Prettier ordering hierarchy.',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 167,
    slug: 'fluid-typography',
    name: 'CSS Fluid Typography & Clamp Calculator',
    shortDescription: 'Calculate responsive CSS clamp() formulas for fluid font sizes across viewport breakpoints.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 168,
    slug: 'css-media-query-builder',
    name: 'CSS Media Query Range Builder',
    shortDescription: 'Build modern range-syntax CSS @media queries with dark mode and motion preference filters.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 169,
    slug: 'css-grid-area-builder',
    name: 'CSS Grid Template Areas Builder',
    shortDescription: 'Generate visual CSS grid-template-areas layout declarations and responsive area matrices.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 170,
    slug: 'css-cubic-bezier',
    name: 'CSS Cubic-Bezier Curve Designer',
    shortDescription: 'Design and preview custom cubic-bezier timing functions with spring and bounce presets.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 171,
    slug: 'color-harmony-generator',
    name: 'Color Harmony & Palette Generator',
    shortDescription: 'Generate complementary, triadic, and analogous color harmonies with hex and HSL codes.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 172,
    slug: 'json-to-pydantic',
    name: 'JSON to Python Pydantic V2 Model',
    shortDescription: 'Convert JSON payloads into type-safe Python Pydantic V2 BaseModel class definitions.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 173,
    slug: 'json-to-rust-serde',
    name: 'JSON to Rust Serde Struct Converter',
    shortDescription: 'Convert JSON objects into Rust struct definitions with serde derive attributes.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 174,
    slug: 'json-to-swift',
    name: 'JSON to Swift Codable Struct Converter',
    shortDescription: 'Convert JSON API responses into Swift Codable and Identifiable data structs.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 175,
    slug: 'json-to-kotlin',
    name: 'JSON to Kotlin Data Class Converter',
    shortDescription: 'Convert JSON into Kotlin data classes with @Serializable and @SerialName annotations.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 176,
    slug: 'json-to-csharp',
    name: 'JSON to C# Class Converter',
    shortDescription: 'Convert JSON into strongly-typed C# classes with System.Text.Json attributes.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 177,
    slug: 'json-to-java-pojo',
    name: 'JSON to Java Lombok POJO Converter',
    shortDescription: 'Convert JSON objects into Java POJO classes with Lombok @Data and Jackson annotations.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 178,
    slug: 'typescript-to-json-schema',
    name: 'TypeScript to JSON Schema Converter',
    shortDescription: 'Convert TypeScript interface definitions into standard JSON Schema Draft 7/2020-12.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 179,
    slug: 'yaml-to-typescript',
    name: 'YAML to TypeScript Interface Converter',
    shortDescription: 'Convert YAML configuration documents directly into typed TypeScript interfaces.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 180,
    slug: 'graphql-to-typescript',
    name: 'GraphQL SDL to TypeScript Types Converter',
    shortDescription: 'Convert GraphQL schema definition language (SDL) types into TypeScript interfaces.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 181,
    slug: 'protobuf-to-json',
    name: 'Protobuf (proto3) to JSON Schema Converter',
    shortDescription: 'Convert Protocol Buffer message schemas into standard JSON Schema definitions.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 182,
    slug: 'sql-to-mongodb',
    name: 'SQL to MongoDB Query Converter',
    shortDescription: 'Convert SQL SELECT and WHERE queries into MongoDB db.collection.find() syntax.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 183,
    slug: 'json-to-sql-ddl',
    name: 'JSON to SQL CREATE TABLE DDL Generator',
    shortDescription: 'Infer database column types from JSON data and generate SQL CREATE TABLE DDL schemas.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 184,
    slug: 'sql-explainer',
    name: 'SQL Query Visual Explainer',
    shortDescription: 'Break down complex SQL SELECT joins, filters, and aggregations into plain English steps.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 185,
    slug: 'postgres-connection-builder',
    name: 'PostgreSQL Connection URI Builder & Parser',
    shortDescription: 'Build and parse PostgreSQL database connection strings and parameters.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 186,
    slug: 'redis-command-generator',
    name: 'Redis Command Builder & Key Helper',
    shortDescription: 'Build Redis CLI commands for hashes, sets, sorted sets, lists, and expiration TTL.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 187,
    slug: 'csv-to-parquet-schema',
    name: 'CSV to Apache Parquet Schema Converter',
    shortDescription: 'Inspect CSV headers and generate PyArrow Apache Parquet schema declarations.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 188,
    slug: 'mongodb-objectid-parser',
    name: 'MongoDB ObjectId Timestamp & Metadata Parser',
    shortDescription: 'Extract creation timestamps, machine identifiers, and process IDs from MongoDB ObjectIds.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 189,
    slug: 'sql-index-advisor',
    name: 'SQL B-Tree Composite Index Advisor',
    shortDescription: 'Analyze SQL WHERE and JOIN clauses to recommend optimal B-Tree composite database indexes.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 190,
    slug: 'postgres-to-mysql',
    name: 'PostgreSQL to MySQL Dialect Converter',
    shortDescription: 'Convert PostgreSQL SQL dialect and data types into MySQL compatible schema syntax.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 191,
    slug: 'prisma-to-sql',
    name: 'Prisma Schema to SQL DDL Generator',
    shortDescription: 'Convert Prisma ORM schema models into raw SQL CREATE TABLE statements.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 192,
    slug: 'docker-compose-to-k8s',
    name: 'Docker Compose to Kubernetes YAML Converter',
    shortDescription: 'Convert docker-compose.yml services into Kubernetes Deployment and Service manifests.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 193,
    slug: 'nginx-formatter',
    name: 'Nginx Config Formatter & Validator',
    shortDescription: 'Format and indent Nginx server blocks, location directives, and upstream configurations.',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 194,
    slug: 'terraform-formatter',
    name: 'Terraform HCL Formatter & Linter',
    shortDescription: 'Format HashiCorp Terraform (.tf) configuration files with standard 2-space indentation.',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 195,
    slug: 'kubeconfig-validator',
    name: 'Kubernetes Kubeconfig Validator',
    shortDescription: 'Validate Kubeconfig YAML files, cluster contexts, server endpoints, and user credentials.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 196,
    slug: 'helm-values-evaluator',
    name: 'Helm Template & Values.yaml Evaluator',
    shortDescription: 'Simulate Helm template variable interpolation with custom values.yaml payloads.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 197,
    slug: 'dockerfile-linter',
    name: 'Dockerfile Linter & Best-Practice Checker',
    shortDescription: 'Analyze Dockerfiles for caching issues, layer bloat, and container security best practices.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 198,
    slug: 'systemd-unit-generator',
    name: 'Linux Systemd Service Unit Generator',
    shortDescription: 'Generate systemd .service unit configuration files for Node.js, Python, and Go daemons.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 199,
    slug: 'caddy-to-nginx',
    name: 'Caddyfile to Nginx Reverse Proxy Converter',
    shortDescription: 'Convert Caddy reverse proxy blocks into production-ready Nginx server configurations.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 200,
    slug: 'aws-iam-policy-builder',
    name: 'AWS IAM Policy JSON Builder & Validator',
    shortDescription: 'Build and validate AWS IAM JSON policy statements with Effect, Action, and Resource fields.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 201,
    slug: 'prometheus-alert-builder',
    name: 'Prometheus Alert Rule & PromQL Builder',
    shortDescription: 'Generate Prometheus alerting rule YAML manifests with PromQL expressions and labels.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 202,
    slug: 'websocket-tester',
    name: 'WebSocket Client & Latency Tester',
    shortDescription: 'Connect to wss:// WebSocket endpoints, send JSON payloads, and monitor message logs.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 203,
    slug: 'curl-to-postman',
    name: 'cURL to Postman Collection Converter',
    shortDescription: 'Convert cURL command strings into importable Postman v2.1 Collection JSON files.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 204,
    slug: 'ssl-certificate-inspector',
    name: 'SSL Certificate PEM & SANs Inspector',
    shortDescription: 'Inspect x509 PEM SSL/TLS certificates for validity, issuer, Subject Alternative Names, and expiry.',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 205,
    slug: 'csr-generator',
    name: 'CSR (Certificate Signing Request) Builder',
    shortDescription: 'Generate OpenSSL Certificate Signing Request commands with Common Name and SAN domains.',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 206,
    slug: 'sse-stream-tester',
    name: 'Server-Sent Events (SSE) Stream Tester',
    shortDescription: 'Test real-time Server-Sent Events (SSE) streams and inspect incoming EventSource chunks.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 207,
    slug: 'graphql-query-formatter',
    name: 'GraphQL Query Formatter & Minifier',
    shortDescription: 'Prettify or minify GraphQL queries, mutations, subscriptions, and fragments.',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 208,
    slug: 'har-viewer',
    name: 'HAR (HTTP Archive) File Viewer & Analyzer',
    shortDescription: 'Parse HTTP Archive (.har) logs to inspect request timelines, headers, and status codes.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 209,
    slug: 'dns-lookup-simulator',
    name: 'DNS Records & Propagation Simulator',
    shortDescription: 'Simulate DNS lookups for A, AAAA, CNAME, MX, TXT, and NS records with TTL durations.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 210,
    slug: 'http-wire-format',
    name: 'HTTP Request to Raw Wire Format Converter',
    shortDescription: 'Convert structured HTTP requests into raw HTTP/1.1 wire transmission text payloads.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 211,
    slug: 'webhook-signature-verifier',
    name: 'HMAC Webhook Signature Verifier',
    shortDescription: 'Verify Stripe, GitHub, and Shopify HMAC SHA-256 webhook payload signatures.',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 212,
    slug: 'uuid-v7-generator',
    name: 'UUID v7 Generator (Time-Ordered)',
    shortDescription: 'Generate modern Unix Epoch time-ordered UUIDv7 identifiers and extract timestamps.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 213,
    slug: 'nanoid-generator',
    name: 'NanoID Generator & Custom Alphabet Builder',
    shortDescription: 'Generate compact, URL-friendly, cryptographically secure NanoIDs with custom alphabets.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 214,
    slug: 'base58-encoder',
    name: 'Base58 Encoder & Decoder (Bitcoin / Solana / IPFS)',
    shortDescription: 'Encode and decode plain text and raw bytes to Base58 and Base58Check formats.',
    categorySlug: 'encoding',
    categoryName: 'Encoder Online',
    isFeatured: true,
  },
  {
    id: 215,
    slug: 'ssh-key-inspector',
    name: 'SSH Public Key Fingerprint Inspector',
    shortDescription: 'Parse OpenSSH public keys to extract key algorithms, comments, and SHA-256 fingerprints.',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 216,
    slug: 'pgp-key-inspector',
    name: 'PGP & GPG Key Block Inspector',
    shortDescription: 'Validate and inspect ASCII-armored PGP public/private keys and encrypted message blocks.',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 217,
    slug: 'api-key-generator',
    name: 'API Key & Token Generator (Prefix-Ready)',
    shortDescription: 'Generate cryptographically random API keys and session secrets with custom prefixes.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 218,
    slug: 'jwt-signature-validator',
    name: 'JWT Signature & Expiry Validator',
    shortDescription: 'Inspect JWT headers, claims, and verify token structure and expiration timestamps.',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 219,
    slug: 'aes-crypto-playground',
    name: 'AES-256 Encryption & Decryption Playground',
    shortDescription: 'Generate 256-bit AES cryptographic keys and test AES-GCM encryption parameters.',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 220,
    slug: 'bip39-seed-deriver',
    name: 'BIP-39 Mnemonic to Seed Deriver',
    shortDescription: 'Derive 512-bit binary seed hex strings from 12 and 24-word BIP-39 mnemonic phrases.',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 221,
    slug: 'argon2-hash-generator',
    name: 'Argon2 Password Hash Formatter',
    shortDescription: 'Format Argon2id password hashes with custom memory cost, time iterations, and parallelism.',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 222,
    slug: 'android-manifest-builder',
    name: 'Android Manifest XML & Permissions Builder',
    shortDescription: 'Generate AndroidManifest.xml files with permissions, activities, and launcher intent filters.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 223,
    slug: 'ios-plist-builder',
    name: 'iOS Info.plist Permission Key Builder',
    shortDescription: 'Build iOS Info.plist XML files with standard permission usage descriptions.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 224,
    slug: 'app-icon-resizer',
    name: 'App Icon Resolution Package Reference',
    shortDescription: 'View standard iOS App Store and Android Play Store icon size specifications.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 225,
    slug: 'universal-links-validator',
    name: 'Apple Universal Links & Android App Links Generator',
    shortDescription: 'Generate apple-app-site-association and assetlinks.json deep link configuration files.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 226,
    slug: 'flutter-theme-generator',
    name: 'Flutter Material 3 ColorScheme Generator',
    shortDescription: 'Convert hex color palettes into Flutter Material 3 ThemeData ColorScheme code.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 227,
    slug: 'xcode-asset-catalog',
    name: 'Xcode Asset Catalog Contents.json Builder',
    shortDescription: 'Generate standard 1x, 2x, 3x image asset catalog Contents.json manifests for iOS apps.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 228,
    slug: 'android-keystore-fingerprint',
    name: 'Android Keystore Fingerprint (SHA1/SHA256) Formatter',
    shortDescription: 'Format Keystore SHA-1 and SHA-256 certificate fingerprints for Firebase and Google OAuth.',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 229,
    slug: 'electron-config-builder',
    name: 'Electron main.js & App Window Builder',
    shortDescription: 'Generate Electron starter main.js files with BrowserWindow and security configurations.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 230,
    slug: 'react-native-icon-finder',
    name: 'React Native Vector Icons Finder & Code Generator',
    shortDescription: 'Search and export icon names and JSX import tags for react-native-vector-icons.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 231,
    slug: 'capacitor-config-builder',
    name: 'Capacitor capacitor.config.json Builder',
    shortDescription: 'Build capacitor.config.json configuration files for hybrid iOS and Android mobile apps.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 232,
    slug: 'code-side-by-side-diff',
    name: 'Code Side-by-Side Diff Visualizer',
    shortDescription: 'Compare two code snippets side-by-side with line-by-line difference tracking.',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 233,
    slug: 'conventional-commit-builder',
    name: 'Conventional Git Commit Message Builder',
    shortDescription: 'Build standard Conventional Commits with feat, fix, scope, and breaking change footers.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 234,
    slug: 'git-command-builder',
    name: 'Git Interactive Command Generator',
    shortDescription: 'Generate Git commands for interactive rebase, cherry-pick, hard reset, and stashing.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 235,
    slug: 'env-sanitizer',
    name: '.env to .env.example Secret Sanitizer',
    shortDescription: 'Strip private API keys and database credentials from .env files to produce .env.example templates.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 236,
    slug: 'license-generator',
    name: 'Open Source License & SPDX Generator',
    shortDescription: 'Generate MIT, Apache 2.0, and GPL open source software license texts with copyright headers.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 237,
    slug: 'eslint-prettier-config',
    name: 'Prettier & ESLint Configuration Builder',
    shortDescription: 'Generate customized .prettierrc JSON configuration files with single quotes and tab width.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 238,
    slug: 'markdown-to-slides',
    name: 'Markdown to HTML Slide Deck Converter',
    shortDescription: 'Convert markdown files separated by horizontal rules into responsive HTML presentation slides.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 239,
    slug: 'package-json-formatter',
    name: 'Package.json Dependency Sorter & Prettifier',
    shortDescription: 'Alphabetically sort dependencies and format package.json files cleanly.',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 240,
    slug: 'changelog-generator',
    name: 'CHANGELOG.md Builder (Keep a Changelog)',
    shortDescription: 'Generate versioned changelog markdown following Keep a Changelog guidelines.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 241,
    slug: 'editorconfig-generator',
    name: '.editorconfig File Generator',
    shortDescription: 'Generate .editorconfig files with cross-editor indentation, charset, and newline rules.',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 242,
    slug: 'ieee754-visualizer',
    name: 'IEEE 754 Floating Point 32-bit Visualizer',
    shortDescription: 'Break down 32-bit float numbers into sign, exponent, and mantissa binary bits.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 243,
    slug: 'bitwise-calculator',
    name: 'Bitwise Logic Calculator (AND, OR, XOR, Shift)',
    shortDescription: 'Perform 32-bit bitwise AND, OR, XOR, NOT, and bit shifts with binary and hex results.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 244,
    slug: 'hex-dump-viewer',
    name: 'Hex Dump Viewer & Binary Offset Inspector',
    shortDescription: 'Format text strings into classic 16-byte offset hex dump and ASCII sidebar views.',
    categorySlug: 'encoding',
    categoryName: 'Encoder Online',
    isFeatured: true,
  },
  {
    id: 245,
    slug: 'bignumber-calculator',
    name: 'Arbitrary Precision BigNumber Calculator',
    shortDescription: 'Perform exact arbitrary precision integer math, powers, and modulo arithmetic.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 246,
    slug: 'multi-radix-converter',
    name: 'Multi-Radix Base Converter (Bin, Oct, Dec, Hex)',
    shortDescription: 'Simultaneously convert numbers across Binary, Octal, Decimal, and Hexadecimal representations.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 247,
    slug: 'timezone-meeting-planner',
    name: 'Timezone Meeting Planner & Overlap Matrix',
    shortDescription: 'Coordinate global meeting hours across UTC, EST, PST, CET, TRT, and JST timezones.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 248,
    slug: 'bandwidth-calculator',
    name: 'Bandwidth & File Download Time Calculator',
    shortDescription: 'Calculate file transfer durations for file sizes over Mbps and Gbps internet speeds.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 249,
    slug: 'percentage-growth-calculator',
    name: 'Percentage Growth & Change Calculator',
    shortDescription: 'Calculate percentage increases, decreases, and compound metrics for dashboards.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 250,
    slug: 'cron-timezone-converter',
    name: 'Cron Expression Timezone Converter (Local ↔ UTC)',
    shortDescription: 'Shift cron expression hours between local timezones and server UTC schedules.',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 251,
    slug: 'matrix-calculator',
    name: 'Matrix Arithmetic & Transpose Calculator',
    shortDescription: 'Perform matrix multiplication, dimensions check, and matrix transposition calculations.',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
] as const satisfies readonly Tool[];

export type ToolSlug = (typeof toolCatalog)[number]['slug'];

const categoryBySlug = new Map<string, Category>(
  categoryCatalog.map((category) => [category.slug, category]),
);
const toolBySlug = new Map<string, Tool>(toolCatalog.map((tool) => [tool.slug, tool]));

export function findCatalogTool(slug: string): Tool | undefined {
  return toolBySlug.get(slug);
}

export function isToolSlug(slug: string): slug is ToolSlug {
  return toolBySlug.has(slug);
}

const curatedRelatedToolSlugs: Record<string, string[]> = {

  'json-formatter': ['json-validator', 'json-to-typescript', 'json-csv'],
  'json-to-typescript': ['json-to-zod', 'json-to-env', 'sql-to-typescript'],
  'json-csv': ['csv-to-markdown', 'csv-to-sql-insert', 'csv-column-extractor'],
  'sql-formatter': ['sql-minifier', 'sql-to-typescript', 'json-to-sql'],
  'jwt-decoder': ['certificate-decoder', 'hmac-generator', 'base64'],
  'base64': ['hex-to-base64', 'base32-encoder', 'base64-to-pdf'],
  'image-to-base64': ['base64-to-pdf', 'base64-to-image', 'favicon-generator'],
  'hex-encoder': ['hex-to-base64', 'binary-encoder', 'number-base-converter'],
  'binary-encoder': ['hex-encoder', 'roman-numeral-converter', 'number-base-converter'],
  'number-base-converter': ['hex-encoder', 'binary-encoder', 'roman-numeral-converter'],
  'regex-tester': ['regex-escape', 'text-diff', 'case-converter'],
  'regex-escape': ['regex-tester', 'text-diff', 'case-converter'],
  'uuid-generator': ['password-generator', 'qr-code', 'slug-generator'],
  'password-generator': ['password-strength-analyzer', 'bcrypt-generator', 'bip39-generator'],
  'slug-generator': ['slug-to-title', 'ulid-generator', 'ascii-art-generator'],
  'qr-code': ['totp-generator', 'url-encoder', 'uuid-generator'],
  'lorem-ipsum': ['ascii-art-generator', 'mock-data-generator', 'slug-generator'],
  'word-counter': ['string-byte-counter', 'text-obfuscator', 'case-converter'],
  'markdown-preview': ['markdown-table-to-csv', 'html-to-markdown', 'word-counter'],
  'sort-lines': ['remove-duplicates', 'text-diff', 'word-counter'],
  'remove-duplicates': ['sort-lines', 'markdown-preview', 'text-diff'],
  'text-diff': ['sort-lines', 'remove-duplicates', 'lorem-ipsum'],
  'url-encoder': ['punycode-converter', 'url-parser', 'query-string-parser'],
  'meta-tags': ['open-graph-previewer', 'robots-txt-generator', 'favicon-generator'],
  'md5-hash': ['sha256-hash', 'sha512-hash', 'hmac-generator'],
  'sha256-hash': ['sha512-hash', 'md5-hash', 'hmac-generator'],
  'sha512-hash': ['sha256-hash', 'hmac-generator', 'md5-hash'],
  'hmac-generator': ['jwt-generator', 'bcrypt-generator', 'pkce-generator'],
  'url-parser': ['query-string-parser', 'punycode-converter', 'user-agent-parser'],
  'query-string-parser': ['url-parser', 'url-encoder', 'user-agent-parser'],
  'http-headers-parser': ['http-status-codes', 'curl-builder', 'dmarc-generator'],
  'user-agent-parser': ['key-code-info', 'cidr-calculator', 'url-parser'],
  'http-status-codes': ['http-headers-parser', 'cache-control', 'curl-to-fetch'],
  'pkce-generator': ['jwt-generator', 'sha256-hash', 'hmac-generator'],
  'cidr-calculator': ['ipv6-subnet-calculator', 'ip-subnet-calculator', 'url-parser'],
  'json-pointer': ['json-diff-patch', 'jsonpath-tester', 'json-size-analyzer'],
  'jsonpath-tester': ['json-diff-patch', 'json-pointer', 'json-size-analyzer'],
  'chmod-calculator': ['semver-calculator', 'key-code-info', 'cron-generator'],
  'cache-control': ['http-headers-parser', 'csp-builder', 'curl-to-fetch'],
  'csp-builder': ['dns-record-generator', 'cache-control', 'dmarc-generator'],
  'curl-to-fetch': ['curl-to-code', 'curl-builder', 'http-status-codes'],
  'yaml-json': ['xml-to-json', 'tsv-to-json', 'env-to-json'],
  'env-to-json': ['json-to-env', 'yaml-json', 'docker-run-to-compose'],
  'json-to-zod': ['json-schema-validator', 'json-to-typescript', 'json-to-graphql'],
  'bcrypt-generator': ['bcrypt-verifier', 'password-strength-analyzer', 'htpasswd-generator'],
  'json-diff-patch': ['json-size-analyzer', 'json-pointer', 'json-validator'],
  'json-schema-validator': ['json-validator', 'json-to-zod', 'openapi-validator'],
  'color-contrast-checker': ['color-palette-generator', 'color-converter', 'css-gradient'],
  'certificate-decoder': ['rsa-key-pair-generator', 'jwt-decoder', 'sha256-hash'],
  'openapi-validator': ['json-schema-validator', 'json-to-graphql', 'curl-to-code'],
  'color-converter': ['color-palette-generator', 'css-filter-generator', 'color-contrast-checker'],
  'css-gradient': ['css-mesh-gradient', 'css-pattern-generator', 'color-contrast-checker'],
  'html-formatter': ['html-to-jsx', 'xml-formatter', 'html-to-markdown'],
  'html-minifier': ['sql-minifier', 'json-minifier', 'js-minifier'],
  'xml-formatter': ['xml-to-json', 'html-formatter', 'html-minifier'],
  'css-minifier': ['css-scrollbar-generator', 'css-clip-path', 'js-minifier'],
  'js-minifier': ['html-minifier', 'css-minifier', 'json-minifier'],
  'unicode-escape': ['json-string-escape', 'text-obfuscator', 'html-entity'],
  'json-string-escape': ['unicode-escape', 'html-entity', 'json-formatter'],
  'case-converter': ['slug-to-title', 'regex-tester', 'regex-escape'],
  'html-entity': ['json-string-escape', 'unicode-escape', 'html-to-jsx'],
  'svg-to-jsx': ['html-to-jsx', 'svg-path-visualizer', 'svg-to-png'],
  'svg-minifier': ['svg-optimizer', 'svg-to-jsx', 'html-minifier'],
  'css-clamp': ['css-scrollbar-generator', 'css-flexbox-generator', 'px-to-rem'],
  'css-box-shadow': ['css-neumorphism', 'css-clip-path', 'css-text-shadow'],
  'docker-run-to-compose': ['dockerfile-generator', 'gitignore-generator', 'env-to-json'],
  'cron-generator': ['crontab-descriptor', 'cron-parser', 'time-duration-calculator'],
  'cron-parser': ['crontab-descriptor', 'cron-generator', 'timestamp-converter'],
  'timestamp-converter': ['time-duration-calculator', 'cron-parser', 'cron-generator'],
  'json-to-sql': ['csv-to-sql-insert', 'list-to-sql-in', 'sql-to-json'],
  'bip39-generator': ['ulid-generator', 'totp-generator', 'password-generator'],
  'dmarc-generator': ['dns-record-generator', 'robots-txt-generator', 'csp-builder'],
  'json-to-models': ['sql-to-typescript', 'mock-data-generator', 'json-to-zod'],
  'px-to-rem': ['aspect-ratio-calculator', 'css-grid-generator', 'css-clamp'],
  'mock-data-generator': ['uuid-generator', 'json-formatter', 'json-to-models'],
  'csv-to-markdown': ['markdown-table-to-csv', 'csv-column-extractor', 'csv-to-sql-insert'],
  'curl-to-code': ['curl-builder', 'curl-to-fetch', 'openapi-validator'],
  'rsa-key-pair-generator': ['certificate-decoder', 'hmac-generator', 'sha256-hash'],
  'svg-optimizer': ['svg-path-visualizer', 'svg-to-png', 'svg-placeholder-generator'],
  'html-table-to-json': ['markdown-table-to-csv', 'sql-to-json', 'csv-to-markdown'],
  'favicon-generator': ['svg-placeholder-generator', 'base64-to-image', 'image-to-base64'],
  'gitignore-generator': ['dockerfile-generator', 'slug-generator', 'uuid-generator'],
  'htpasswd-generator': ['htaccess-to-nginx', 'bcrypt-verifier', 'bcrypt-generator'],
  'dockerfile-generator': ['htaccess-to-nginx', 'docker-run-to-compose', 'gitignore-generator'],
  'css-glassmorphism': ['css-filter-generator', 'css-neumorphism', 'css-border-radius'],
  'css-grid-generator': ['css-flexbox-generator', 'css-pattern-generator', 'css-glassmorphism'],
  'css-blob-generator': ['css-clip-path', 'css-border-radius', 'css-triangle-generator'],
  'robots-txt-generator': ['open-graph-previewer', 'sitemap-generator', 'meta-tags'],
  'sitemap-generator': ['robots-txt-generator', 'url-parser', 'meta-tags'],
  'sql-to-json': ['sql-to-typescript', 'list-to-sql-in', 'json-to-sql'],
  'totp-generator': ['base32-encoder', 'htpasswd-generator', 'qr-code'],
  'markdown-table-generator': ['markdown-table-to-csv', 'markdown-to-html', 'html-table-to-json'],
  'key-code-info': ['cidr-calculator', 'user-agent-parser', 'chmod-calculator'],
  'aspect-ratio-calculator': ['px-to-rem', 'css-clamp', 'svg-placeholder-generator'],
  'base64-to-image': ['base64-to-pdf', 'hex-to-base64', 'image-to-base64'],
  'html-to-markdown': ['html-table-to-json', 'markdown-to-html', 'markdown-table-generator'],
  'css-triangle-generator': ['css-clip-path', 'css-animation-generator', 'css-blob-generator'],
  'svg-placeholder-generator': ['svg-path-visualizer', 'aspect-ratio-calculator', 'favicon-generator'],
  'css-flexbox-generator': ['css-grid-generator', 'css-clamp', 'css-glassmorphism'],
  'open-graph-previewer': ['meta-tags', 'robots-txt-generator', 'sitemap-generator'],
  'ascii-art-generator': ['morse-code-converter', 'slug-generator', 'lorem-ipsum'],
  'css-animation-generator': ['css-triangle-generator', 'css-text-shadow', 'css-blob-generator'],
  'markdown-to-html': ['html-to-markdown', 'markdown-preview', 'markdown-table-generator'],
  'css-text-shadow': ['css-box-shadow', 'css-animation-generator', 'color-converter'],
  'time-duration-calculator': ['crontab-descriptor', 'timestamp-converter', 'cron-generator'],
  'xml-to-json': ['xml-formatter', 'tsv-to-json', 'ndjson-to-json'],
  'list-to-sql-in': ['csv-to-sql-insert', 'json-to-sql', 'sql-to-json'],
  'svg-to-png': ['svg-minifier', 'svg-to-jsx', 'svg-optimizer'],
  'ip-subnet-calculator': ['ipv6-subnet-calculator', 'mac-address-generator', 'cidr-calculator'],
  'css-filter-generator': ['css-pattern-generator', 'css-mesh-gradient', 'css-gradient'],
  'bcrypt-verifier': ['password-strength-analyzer', 'bcrypt-generator', 'htpasswd-generator'],
  'css-border-radius': ['css-clip-path', 'css-neumorphism', 'css-blob-generator'],
  'jwt-generator': ['jwt-decoder', 'rsa-key-pair-generator', 'pkce-generator'],
  'ulid-generator': ['uuid-generator', 'timestamp-converter', 'slug-generator'],
  'curl-builder': ['htaccess-to-nginx', 'curl-to-code', 'curl-to-fetch'],
  'base64-to-pdf': ['base64-to-image', 'hex-to-base64', 'base64'],
  'css-neumorphism': ['css-glassmorphism', 'css-box-shadow', 'css-border-radius'],
  'string-byte-counter': ['text-obfuscator', 'word-counter', 'case-converter'],
  'css-mesh-gradient': ['css-pattern-generator', 'css-gradient', 'css-glassmorphism'],
  'html-to-jsx': ['svg-to-jsx', 'html-formatter', 'html-to-markdown'],
  'css-clip-path': ['css-triangle-generator', 'css-blob-generator', 'css-border-radius'],
  'css-scrollbar-generator': ['css-minifier', 'css-box-shadow', 'css-clamp'],
  'css-pattern-generator': ['css-gradient', 'css-mesh-gradient', 'css-grid-generator'],
  'svg-path-visualizer': ['svg-minifier', 'svg-optimizer', 'svg-placeholder-generator'],
  'color-palette-generator': ['color-converter', 'color-contrast-checker', 'css-gradient'],
  'csv-to-sql-insert': ['csv-column-extractor', 'list-to-sql-in', 'json-to-sql'],
  'sql-minifier': ['sql-formatter', 'html-minifier', 'json-minifier'],
  'json-to-graphql': ['json-to-typescript', 'json-to-models', 'openapi-validator'],
  'tsv-to-json': ['json-csv', 'ndjson-to-json', 'csv-column-extractor'],
  'ndjson-to-json': ['tsv-to-json', 'json-size-analyzer', 'json-formatter'],
  'json-size-analyzer': ['json-minifier', 'jsonpath-tester', 'json-formatter'],
  'hex-to-base64': ['base64', 'hex-encoder', 'base32-encoder'],
  'punycode-converter': ['url-parser', 'url-encoder', 'dns-record-generator'],
  'morse-code-converter': ['text-obfuscator', 'ascii-art-generator', 'binary-encoder'],
  'base32-encoder': ['base64', 'hex-to-base64', 'totp-generator'],
  'password-strength-analyzer': ['password-generator', 'bip39-generator', 'bcrypt-generator'],
  'semver-calculator': ['crontab-descriptor', 'chmod-calculator', 'timestamp-converter'],
  'ipv6-subnet-calculator': ['ip-subnet-calculator', 'cidr-calculator', 'mac-address-generator'],
  'mac-address-generator': ['ipv6-subnet-calculator', 'uuid-generator', 'ulid-generator'],
  'crontab-descriptor': ['cron-generator', 'semver-calculator', 'cron-parser'],
  'htaccess-to-nginx': ['dockerfile-generator', 'htpasswd-generator', 'curl-builder'],
  'dns-record-generator': ['dmarc-generator', 'csp-builder', 'punycode-converter'],
  'slug-to-title': ['slug-generator', 'case-converter', 'text-obfuscator'],
  'text-obfuscator': ['morse-code-converter', 'string-byte-counter', 'unicode-escape'],
  'csv-column-extractor': ['csv-to-sql-insert', 'csv-to-markdown', 'tsv-to-json'],
  'sql-to-typescript': ['sql-formatter', 'json-to-typescript', 'json-to-models'],
  'json-to-env': ['env-to-json', 'json-to-typescript', 'json-formatter'],
  'json-minifier': ['json-size-analyzer', 'sql-minifier', 'json-formatter'],
  'markdown-table-to-csv': ['markdown-table-generator', 'csv-to-markdown', 'markdown-preview'],
  'llm-token-counter': ['matrix-calculator', 'openai-function-schema', 'prompt-template-formatter'],
  'openai-function-schema': ['llm-token-counter', 'prompt-template-formatter', 'embedding-similarity'],
  'prompt-template-formatter': ['openai-function-schema', 'embedding-similarity', 'text-chunk-splitter'],
  'embedding-similarity': ['prompt-template-formatter', 'text-chunk-splitter', 'jsonl-dataset-validator'],
  'text-chunk-splitter': ['embedding-similarity', 'jsonl-dataset-validator', 'prompt-format-converter'],
  'jsonl-dataset-validator': ['text-chunk-splitter', 'prompt-format-converter', 'sampling-curve-visualizer'],
  'prompt-format-converter': ['jsonl-dataset-validator', 'sampling-curve-visualizer', 'system-prompt-formatter'],
  'sampling-curve-visualizer': ['prompt-format-converter', 'system-prompt-formatter', 'prompt-diff'],
  'system-prompt-formatter': ['sampling-curve-visualizer', 'prompt-diff', 'css-to-tailwind'],
  'prompt-diff': ['system-prompt-formatter', 'css-to-tailwind', 'tailwind-to-css'],
  'css-to-tailwind': ['prompt-diff', 'tailwind-to-css', 'css-specificity-calculator'],
  'tailwind-to-css': ['css-to-tailwind', 'css-specificity-calculator', 'css-keyframes-generator'],
  'css-specificity-calculator': ['tailwind-to-css', 'css-keyframes-generator', 'tailwind-class-sorter'],
  'css-keyframes-generator': ['css-specificity-calculator', 'tailwind-class-sorter', 'fluid-typography'],
  'tailwind-class-sorter': ['css-keyframes-generator', 'fluid-typography', 'css-media-query-builder'],
  'fluid-typography': ['tailwind-class-sorter', 'css-media-query-builder', 'css-grid-area-builder'],
  'css-media-query-builder': ['fluid-typography', 'css-grid-area-builder', 'css-cubic-bezier'],
  'css-grid-area-builder': ['css-media-query-builder', 'css-cubic-bezier', 'color-harmony-generator'],
  'css-cubic-bezier': ['css-grid-area-builder', 'color-harmony-generator', 'json-to-pydantic'],
  'color-harmony-generator': ['css-cubic-bezier', 'json-to-pydantic', 'json-to-rust-serde'],
  'json-to-pydantic': ['color-harmony-generator', 'json-to-rust-serde', 'json-to-swift'],
  'json-to-rust-serde': ['json-to-pydantic', 'json-to-swift', 'json-to-kotlin'],
  'json-to-swift': ['json-to-rust-serde', 'json-to-kotlin', 'json-to-csharp'],
  'json-to-kotlin': ['json-to-swift', 'json-to-csharp', 'json-to-java-pojo'],
  'json-to-csharp': ['json-to-kotlin', 'json-to-java-pojo', 'typescript-to-json-schema'],
  'json-to-java-pojo': ['json-to-csharp', 'typescript-to-json-schema', 'yaml-to-typescript'],
  'typescript-to-json-schema': ['json-to-java-pojo', 'yaml-to-typescript', 'graphql-to-typescript'],
  'yaml-to-typescript': ['typescript-to-json-schema', 'graphql-to-typescript', 'protobuf-to-json'],
  'graphql-to-typescript': ['yaml-to-typescript', 'protobuf-to-json', 'sql-to-mongodb'],
  'protobuf-to-json': ['graphql-to-typescript', 'sql-to-mongodb', 'json-to-sql-ddl'],
  'sql-to-mongodb': ['protobuf-to-json', 'json-to-sql-ddl', 'sql-explainer'],
  'json-to-sql-ddl': ['sql-to-mongodb', 'sql-explainer', 'postgres-connection-builder'],
  'sql-explainer': ['json-to-sql-ddl', 'postgres-connection-builder', 'redis-command-generator'],
  'postgres-connection-builder': ['sql-explainer', 'redis-command-generator', 'csv-to-parquet-schema'],
  'redis-command-generator': ['postgres-connection-builder', 'csv-to-parquet-schema', 'mongodb-objectid-parser'],
  'csv-to-parquet-schema': ['redis-command-generator', 'mongodb-objectid-parser', 'sql-index-advisor'],
  'mongodb-objectid-parser': ['csv-to-parquet-schema', 'sql-index-advisor', 'postgres-to-mysql'],
  'sql-index-advisor': ['mongodb-objectid-parser', 'postgres-to-mysql', 'prisma-to-sql'],
  'postgres-to-mysql': ['sql-index-advisor', 'prisma-to-sql', 'docker-compose-to-k8s'],
  'prisma-to-sql': ['postgres-to-mysql', 'docker-compose-to-k8s', 'nginx-formatter'],
  'docker-compose-to-k8s': ['prisma-to-sql', 'nginx-formatter', 'terraform-formatter'],
  'nginx-formatter': ['docker-compose-to-k8s', 'terraform-formatter', 'kubeconfig-validator'],
  'terraform-formatter': ['nginx-formatter', 'kubeconfig-validator', 'helm-values-evaluator'],
  'kubeconfig-validator': ['terraform-formatter', 'helm-values-evaluator', 'dockerfile-linter'],
  'helm-values-evaluator': ['kubeconfig-validator', 'dockerfile-linter', 'systemd-unit-generator'],
  'dockerfile-linter': ['helm-values-evaluator', 'systemd-unit-generator', 'caddy-to-nginx'],
  'systemd-unit-generator': ['dockerfile-linter', 'caddy-to-nginx', 'aws-iam-policy-builder'],
  'caddy-to-nginx': ['systemd-unit-generator', 'aws-iam-policy-builder', 'prometheus-alert-builder'],
  'aws-iam-policy-builder': ['caddy-to-nginx', 'prometheus-alert-builder', 'websocket-tester'],
  'prometheus-alert-builder': ['aws-iam-policy-builder', 'websocket-tester', 'curl-to-postman'],
  'websocket-tester': ['prometheus-alert-builder', 'curl-to-postman', 'ssl-certificate-inspector'],
  'curl-to-postman': ['websocket-tester', 'ssl-certificate-inspector', 'csr-generator'],
  'ssl-certificate-inspector': ['curl-to-postman', 'csr-generator', 'sse-stream-tester'],
  'csr-generator': ['ssl-certificate-inspector', 'sse-stream-tester', 'graphql-query-formatter'],
  'sse-stream-tester': ['csr-generator', 'graphql-query-formatter', 'har-viewer'],
  'graphql-query-formatter': ['sse-stream-tester', 'har-viewer', 'dns-lookup-simulator'],
  'har-viewer': ['graphql-query-formatter', 'dns-lookup-simulator', 'http-wire-format'],
  'dns-lookup-simulator': ['har-viewer', 'http-wire-format', 'webhook-signature-verifier'],
  'http-wire-format': ['dns-lookup-simulator', 'webhook-signature-verifier', 'uuid-v7-generator'],
  'webhook-signature-verifier': ['http-wire-format', 'uuid-v7-generator', 'nanoid-generator'],
  'uuid-v7-generator': ['webhook-signature-verifier', 'nanoid-generator', 'base58-encoder'],
  'nanoid-generator': ['uuid-v7-generator', 'base58-encoder', 'ssh-key-inspector'],
  'base58-encoder': ['nanoid-generator', 'ssh-key-inspector', 'pgp-key-inspector'],
  'ssh-key-inspector': ['base58-encoder', 'pgp-key-inspector', 'api-key-generator'],
  'pgp-key-inspector': ['ssh-key-inspector', 'api-key-generator', 'jwt-signature-validator'],
  'api-key-generator': ['pgp-key-inspector', 'jwt-signature-validator', 'aes-crypto-playground'],
  'jwt-signature-validator': ['api-key-generator', 'aes-crypto-playground', 'bip39-seed-deriver'],
  'aes-crypto-playground': ['jwt-signature-validator', 'bip39-seed-deriver', 'argon2-hash-generator'],
  'bip39-seed-deriver': ['aes-crypto-playground', 'argon2-hash-generator', 'android-manifest-builder'],
  'argon2-hash-generator': ['bip39-seed-deriver', 'android-manifest-builder', 'ios-plist-builder'],
  'android-manifest-builder': ['argon2-hash-generator', 'ios-plist-builder', 'app-icon-resizer'],
  'ios-plist-builder': ['android-manifest-builder', 'app-icon-resizer', 'universal-links-validator'],
  'app-icon-resizer': ['ios-plist-builder', 'universal-links-validator', 'flutter-theme-generator'],
  'universal-links-validator': ['app-icon-resizer', 'flutter-theme-generator', 'xcode-asset-catalog'],
  'flutter-theme-generator': ['universal-links-validator', 'xcode-asset-catalog', 'android-keystore-fingerprint'],
  'xcode-asset-catalog': ['flutter-theme-generator', 'android-keystore-fingerprint', 'electron-config-builder'],
  'android-keystore-fingerprint': ['xcode-asset-catalog', 'electron-config-builder', 'react-native-icon-finder'],
  'electron-config-builder': ['android-keystore-fingerprint', 'react-native-icon-finder', 'capacitor-config-builder'],
  'react-native-icon-finder': ['electron-config-builder', 'capacitor-config-builder', 'code-side-by-side-diff'],
  'capacitor-config-builder': ['react-native-icon-finder', 'code-side-by-side-diff', 'conventional-commit-builder'],
  'code-side-by-side-diff': ['capacitor-config-builder', 'conventional-commit-builder', 'git-command-builder'],
  'conventional-commit-builder': ['code-side-by-side-diff', 'git-command-builder', 'env-sanitizer'],
  'git-command-builder': ['conventional-commit-builder', 'env-sanitizer', 'license-generator'],
  'env-sanitizer': ['git-command-builder', 'license-generator', 'eslint-prettier-config'],
  'license-generator': ['env-sanitizer', 'eslint-prettier-config', 'markdown-to-slides'],
  'eslint-prettier-config': ['license-generator', 'markdown-to-slides', 'package-json-formatter'],
  'markdown-to-slides': ['eslint-prettier-config', 'package-json-formatter', 'changelog-generator'],
  'package-json-formatter': ['markdown-to-slides', 'changelog-generator', 'editorconfig-generator'],
  'changelog-generator': ['package-json-formatter', 'editorconfig-generator', 'ieee754-visualizer'],
  'editorconfig-generator': ['changelog-generator', 'ieee754-visualizer', 'bitwise-calculator'],
  'ieee754-visualizer': ['editorconfig-generator', 'bitwise-calculator', 'hex-dump-viewer'],
  'bitwise-calculator': ['ieee754-visualizer', 'hex-dump-viewer', 'bignumber-calculator'],
  'hex-dump-viewer': ['bitwise-calculator', 'bignumber-calculator', 'multi-radix-converter'],
  'bignumber-calculator': ['hex-dump-viewer', 'multi-radix-converter', 'timezone-meeting-planner'],
  'multi-radix-converter': ['bignumber-calculator', 'timezone-meeting-planner', 'bandwidth-calculator'],
  'timezone-meeting-planner': ['multi-radix-converter', 'bandwidth-calculator', 'percentage-growth-calculator'],
  'bandwidth-calculator': ['timezone-meeting-planner', 'percentage-growth-calculator', 'cron-timezone-converter'],
  'percentage-growth-calculator': ['bandwidth-calculator', 'cron-timezone-converter', 'matrix-calculator'],
  'cron-timezone-converter': ['percentage-growth-calculator', 'matrix-calculator', 'llm-token-counter'],
  'matrix-calculator': ['cron-timezone-converter', 'llm-token-counter', 'openai-function-schema'],
};

function relatedToolsFor(tool: Tool, count: number = 3): Tool[] {
  const categoryTools = toolCatalog.filter(
    (candidate) => candidate.categorySlug === tool.categorySlug,
  );
  const categoryIndex = categoryTools.findIndex((candidate) => candidate.slug === tool.slug);
  const categoryRing = categoryTools
    .slice(categoryIndex + 1)
    .concat(categoryTools.slice(0, categoryIndex));
  const globalIndex = toolCatalog.findIndex((candidate) => candidate.slug === tool.slug);
  const globalRing = toolCatalog.slice(globalIndex + 1).concat(toolCatalog.slice(0, globalIndex));
  const candidates = [
    ...(curatedRelatedToolSlugs[tool.slug] || [])
      .map((slug) => toolCatalog.find((candidate) => candidate.slug === slug))
      .filter((candidate): candidate is (typeof toolCatalog)[number] => candidate !== undefined),
    ...categoryRing,
    ...globalRing,
  ];

  const unique = new Map<string, Tool>();
  for (const candidate of candidates) {
    if (candidate.slug !== tool.slug && !unique.has(candidate.slug)) {
      unique.set(candidate.slug, candidate);
    }
  }

  return [...unique.values()].slice(0, count);
}

function asDetail(tool: Tool): ToolDetail {
  return {
    ...tool,
    longDescription: tool.shortDescription,
    keywords: tool.name.split(' '),
    seo: {
      title: `${tool.name} | DevsTools`,
      metaDescription: tool.shortDescription,
    },
    faqs: [],
    relatedTools: relatedToolsFor(tool),
  };
}

// Categories API (static)
export async function getCategories(): Promise<Category[]> {
  return [...categoryCatalog];
}

export async function getCategoryBySlug(slug: string): Promise<Category | null> {
  return categoryBySlug.get(slug) || null;
}

// Tools API (static)
export async function getTools(): Promise<Tool[]> {
  return [...toolCatalog];
}

export async function getToolBySlug(slug: string): Promise<ToolDetail | null> {
  const tool = findCatalogTool(slug);
  return tool ? asDetail(tool) : null;
}

export async function getFeaturedTools(count: number = 10): Promise<Tool[]> {
  return toolCatalog.filter((t) => t.isFeatured).slice(0, count);
}

export async function getPopularTools(count: number = toolCatalog.length): Promise<Tool[]> {
  return toolCatalog.slice(0, count);
}
