export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string;
  icon?: string;
  toolCount: number;
}

export interface Tool {
  id: number;
  name: string;
  slug: string;
  shortDescription?: string;
  categorySlug: string;
  categoryName: string;
  isFeatured: boolean;
}

export interface ToolDetail extends Tool {
  longDescription?: string;
  keywords: string[];
  seo?: {
    title?: string;
    metaDescription?: string;
    ogTitle?: string;
    ogDescription?: string;
    ogImageUrl?: string;
    canonicalUrl?: string;
    structuredData?: string;
  };
  faqs: { question: string; answer: string }[];
  relatedTools?: Tool[];
}

// Static data now that the backend is disabled.
export const categoryCatalog = [
  {
    id: 1,
    slug: 'json',
    name: 'JSON Tools',
    description:
      'JSON formatting, validation, querying, patching, and conversion tools for developers',
    toolCount: 11,
  },
  {
    id: 2,
    slug: 'encoding',
    name: 'Encoder Online',
    description:
      'Encode and decode Base64, URL components, hexadecimal, binary, images, and JSON strings',
    toolCount: 10,
  },
  {
    id: 3,
    slug: 'generators',
    name: 'Generators',
    description: 'UUID, password, mock data, markdown tables, gitignore, blob, and icon generators',
    toolCount: 15,
  },
  {
    id: 4,
    slug: 'crypto',
    name: 'Cryptography',
    description: 'Hashing, message authentication, certificates, htpasswd, 2FA/TOTP, and key pairs',
    toolCount: 11,
  },
  {
    id: 5,
    slug: 'text',
    name: 'Text Tools',
    description: 'Text manipulation and formatting tools',
    toolCount: 8,
  },
  {
    id: 6,
    slug: 'converters',
    name: 'Converters',
    description: 'Data format, CSS unit, aspect ratio, HTML-to-Markdown, SQL, and table converters',
    toolCount: 17,
  },
  {
    id: 7,
    slug: 'formatters',
    name: 'Code Formatters',
    description: 'Format and minify code and SVGs in various languages',
    toolCount: 8,
  },
  {
    id: 8,
    slug: 'utilities',
    name: 'Developer Utilities',
    description: 'HTTP, SEO, robots.txt, keycodes, CSS triangles, Dockerfile, CSS Grid, and utilities',
    toolCount: 20,
  },
] as const satisfies readonly Category[];

export type CategorySlug = (typeof categoryCatalog)[number]['slug'];

export const toolCatalog = [
  {
    id: 1,
    slug: 'json-formatter',
    name: 'JSON Formatter',
    shortDescription: 'Format and beautify JSON data',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 2,
    slug: 'json-validator',
    name: 'JSON Validator',
    shortDescription: 'Validate JSON syntax and structure',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 3,
    slug: 'json-csv',
    name: 'JSON to CSV',
    shortDescription: 'Convert JSON arrays to CSV and back',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 4,
    slug: 'json-to-typescript',
    name: 'JSON to TypeScript',
    shortDescription: 'Generate TypeScript interfaces from JSON',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 5,
    slug: 'base64',
    name: 'Base64 Encoder/Decoder',
    shortDescription: 'Encode or decode Base64 strings',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 6,
    slug: 'url-encoder',
    name: 'URL Encoder/Decoder',
    shortDescription: 'Encode or decode URL strings',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 7,
    slug: 'jwt-decoder',
    name: 'JWT Decoder, Signer & Verifier',
    shortDescription: 'Decode JWTs and sign or verify HS256, HS384, and HS512 tokens locally',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 8,
    slug: 'html-entity',
    name: 'HTML Entity Encoder/Decoder',
    shortDescription: 'Encode or decode HTML entities',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 9,
    slug: 'uuid-generator',
    name: 'UUID v4 & v7 Generator',
    shortDescription: 'Generate random v4 or timestamp-based v7 UUIDs',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 10,
    slug: 'password-generator',
    name: 'Password Generator',
    shortDescription: 'Create strong random passwords',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 11,
    slug: 'qr-code',
    name: 'QR Code Generator',
    shortDescription: 'Create QR codes from text or URLs',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 12,
    slug: 'slug-generator',
    name: 'Slug Generator',
    shortDescription: 'Generate clean URL slugs',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 13,
    slug: 'css-gradient',
    name: 'CSS Gradient',
    shortDescription: 'Design and export CSS gradients',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 14,
    slug: 'meta-tags',
    name: 'Meta Tags Generator',
    shortDescription: 'Generate SEO meta tags',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 15,
    slug: 'md5-hash',
    name: 'MD5 Hash',
    shortDescription: 'Generate MD5 hashes',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 16,
    slug: 'sha256-hash',
    name: 'SHA256 Hash',
    shortDescription: 'Generate SHA256 hashes',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 17,
    slug: 'regex-tester',
    name: 'Regex Tester',
    shortDescription: 'Test and debug regex patterns',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 18,
    slug: 'text-diff',
    name: 'Text Diff',
    shortDescription: 'Compare texts and highlight differences',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 19,
    slug: 'markdown-preview',
    name: 'Markdown Preview',
    shortDescription: 'Preview and convert Markdown to HTML',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 20,
    slug: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    shortDescription: 'Generate placeholder text',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 21,
    slug: 'timestamp-converter',
    name: 'Timestamp Converter',
    shortDescription: 'Convert timestamps to readable dates',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 22,
    slug: 'color-converter',
    name: 'Color Converter',
    shortDescription: 'Convert between HEX, RGB, and HSL',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 23,
    slug: 'image-to-base64',
    name: 'Image to Base64',
    shortDescription: 'Convert images to Base64',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 24,
    slug: 'yaml-json',
    name: 'YAML to JSON',
    shortDescription: 'Convert YAML to JSON and back',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 25,
    slug: 'sql-formatter',
    name: 'SQL Formatter',
    shortDescription: 'Format SQL queries',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 26,
    slug: 'css-minifier',
    name: 'CSS Minifier',
    shortDescription: 'Minify CSS for production',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 27,
    slug: 'js-minifier',
    name: 'JS Minifier',
    shortDescription: 'Minify JavaScript for production',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 28,
    slug: 'cron-parser',
    name: 'Cron Parser',
    shortDescription: 'Parse and explain cron expressions',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 29,
    slug: 'case-converter',
    name: 'Case Converter',
    shortDescription: 'Convert text between different cases',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 30,
    slug: 'word-counter',
    name: 'Word Counter',
    shortDescription: 'Count words, characters, lines, and sentences',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 31,
    slug: 'remove-duplicates',
    name: 'Remove Duplicate Lines',
    shortDescription: 'Remove duplicate lines from text',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 32,
    slug: 'sort-lines',
    name: 'Sort Lines',
    shortDescription: 'Sort lines alphabetically',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 33,
    slug: 'hex-encoder',
    name: 'HEX Encoder/Decoder',
    shortDescription: 'Encode or decode text to or from hexadecimal',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 34,
    slug: 'binary-encoder',
    name: 'Binary Encoder/Decoder',
    shortDescription: 'Encode or decode text to or from binary',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 35,
    slug: 'html-formatter',
    name: 'HTML Formatter',
    shortDescription: 'Format and beautify HTML code',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 36,
    slug: 'html-minifier',
    name: 'HTML Minifier',
    shortDescription: 'Minify HTML code for production',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 37,
    slug: 'xml-formatter',
    name: 'XML Formatter',
    shortDescription: 'Format and beautify XML code',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 38,
    slug: 'sha512-hash',
    name: 'SHA512 Hash Generator',
    shortDescription: 'Generate SHA512 hashes from text',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 39,
    slug: 'roman-numeral-converter',
    name: 'Roman Numeral Converter',
    shortDescription: 'Convert numbers to and from Roman numerals',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 40,
    slug: 'number-base-converter',
    name: 'Number Base Converter',
    shortDescription: 'Convert between decimal, hexadecimal, octal, and binary',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 41,
    slug: 'unicode-escape',
    name: 'Unicode Escape Encoder/Decoder',
    shortDescription: 'Convert text to and from Unicode escape sequences',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 42,
    slug: 'json-string-escape',
    name: 'JSON String Escape',
    shortDescription: 'Escape and unescape JSON string content',
    categorySlug: 'encoding',
    categoryName: 'Encoding & Decoding',
    isFeatured: true,
  },
  {
    id: 43,
    slug: 'regex-escape',
    name: 'Regex Escape',
    shortDescription: 'Escape text for safe use in regular expressions',
    categorySlug: 'text',
    categoryName: 'Text Tools',
    isFeatured: true,
  },
  {
    id: 44,
    slug: 'url-parser',
    name: 'URL Parser',
    shortDescription: 'Parse URLs into protocol, host, path, and query parameters',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 45,
    slug: 'query-string-parser',
    name: 'Query String Parser',
    shortDescription: 'Parse and build URL query strings',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 46,
    slug: 'http-headers-parser',
    name: 'HTTP Headers Parser',
    shortDescription: 'Convert raw HTTP headers to JSON and back',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 47,
    slug: 'http-status-codes',
    name: 'HTTP Status Codes',
    shortDescription: 'Search and reference common HTTP status codes',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 48,
    slug: 'user-agent-parser',
    name: 'User Agent Parser Online',
    shortDescription:
      'Parse browser, OS, engine, device, CPU, and bot fields from one or many User-Agent strings',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 49,
    slug: 'json-schema-validator',
    name: 'JSON Schema Validator',
    shortDescription: 'Validate JSON documents against JSON Schema rules',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 50,
    slug: 'hmac-generator',
    name: 'HMAC Generator & Verifier',
    shortDescription: 'Generate and verify keyed SHA message authentication codes',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 51,
    slug: 'pkce-generator',
    name: 'PKCE Generator & Verifier',
    shortDescription: 'Generate and verify OAuth PKCE S256 verifier and challenge pairs',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 52,
    slug: 'cidr-calculator',
    name: 'IPv4 CIDR Calculator',
    shortDescription: 'Calculate IPv4 network ranges, masks, broadcasts, and usable hosts',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 53,
    slug: 'json-pointer',
    name: 'JSON Pointer Evaluator',
    shortDescription: 'Resolve RFC 6901 JSON Pointer paths against JSON documents',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 54,
    slug: 'chmod-calculator',
    name: 'Chmod Calculator',
    shortDescription: 'Convert Unix file permissions between octal and symbolic modes',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 55,
    slug: 'cache-control',
    name: 'Cache-Control Parser & Builder',
    shortDescription: 'Parse, normalize, and check HTTP Cache-Control directives',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 56,
    slug: 'jsonpath-tester',
    name: 'JSONPath Tester',
    shortDescription:
      'Query JSON with RFC 9535-style paths, wildcards, slices, and recursive descent',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 57,
    slug: 'csp-builder',
    name: 'CSP Header Builder & Analyzer',
    shortDescription: 'Build, normalize, and inspect Content Security Policy headers',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 58,
    slug: 'curl-to-fetch',
    name: 'cURL Builder & Fetch Converter',
    shortDescription: 'Build cURL requests or convert safe cURL input to JavaScript fetch',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 59,
    slug: 'env-to-json',
    name: '.env to JSON Converter',
    shortDescription: 'Convert dotenv variables to JSON and back without uploading secrets',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 60,
    slug: 'json-to-zod',
    name: 'JSON to Zod Schema',
    shortDescription: 'Generate Zod schemas and inferred TypeScript types from JSON samples',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 61,
    slug: 'bcrypt-generator',
    name: 'Bcrypt Generator & Verifier',
    shortDescription: 'Generate salted bcrypt hashes and verify test passwords locally',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 62,
    slug: 'json-diff-patch',
    name: 'JSON Diff & Patch Generator',
    shortDescription: 'Generate and apply RFC 6902 JSON Patch operations locally',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 63,
    slug: 'color-contrast-checker',
    name: 'Color Contrast Checker',
    shortDescription: 'Check WCAG text and UI contrast ratios with a live preview',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 64,
    slug: 'certificate-decoder',
    name: 'PEM / X.509 Certificate Decoder',
    shortDescription:
      'Inspect certificate identities, validity, SANs, algorithms, and fingerprints locally',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 65,
    slug: 'openapi-validator',
    name: 'OpenAPI Validator & Endpoint Explorer',
    shortDescription: 'Validate OpenAPI 3 documents and explore endpoint operations locally',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 66,
    slug: 'svg-to-jsx',
    name: 'SVG to JSX / React Converter',
    shortDescription: 'Convert SVG markup to React JSX/TSX components with custom options',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 67,
    slug: 'svg-minifier',
    name: 'SVG Optimizer & Minifier',
    shortDescription: 'Optimize and shrink SVG file sizes with live rendered preview',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 68,
    slug: 'css-clamp',
    name: 'CSS clamp() Fluid Calculator',
    shortDescription: 'Calculate fluid responsive typography and spacing CSS clamp() values',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 69,
    slug: 'css-box-shadow',
    name: 'CSS Box Shadow Generator',
    shortDescription: 'Create multi-layer box shadows and glassmorphism styling visually',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 70,
    slug: 'docker-run-to-compose',
    name: 'Docker Run to Compose Converter',
    shortDescription: 'Convert docker run commands into docker-compose.yml services',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 71,
    slug: 'cron-generator',
    name: 'Visual Cron Expression Builder',
    shortDescription: 'Build standard cron expressions visually with schedule preview',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 72,
    slug: 'json-to-sql',
    name: 'JSON to SQL Converter',
    shortDescription: 'Generate SQL INSERT queries and CREATE TABLE DDL from JSON data',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 73,
    slug: 'bip39-generator',
    name: 'BIP-39 Mnemonic Generator',
    shortDescription: 'Generate and validate 12/24-word cryptocurrency mnemonic seed phrases',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 74,
    slug: 'dmarc-generator',
    name: 'DMARC & SPF Record Generator',
    shortDescription: 'Generate SPF, DMARC, and DKIM DNS TXT records for domain email security',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 75,
    slug: 'json-to-models',
    name: 'JSON to Multi-Language Models',
    shortDescription: 'Generate Go structs, Python Pydantic, Rust Serde, and C# from JSON',
    categorySlug: 'json',
    categoryName: 'JSON Tools',
    isFeatured: true,
  },
  {
    id: 76,
    slug: 'px-to-rem',
    name: 'PX to REM & EM Converter',
    shortDescription: 'Convert pixel dimensions to REM, EM, VW, VH, and CSS units',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 77,
    slug: 'mock-data-generator',
    name: 'Mock Data JSON Generator',
    shortDescription: 'Generate realistic mock JSON datasets for users, products, and orders',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 78,
    slug: 'csv-to-markdown',
    name: 'CSV to Markdown Table Converter',
    shortDescription: 'Convert CSV and TSV spreadsheets to GitHub-flavored Markdown tables',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 79,
    slug: 'curl-to-code',
    name: 'cURL to Multi-Language Code',
    shortDescription: 'Convert cURL commands to JavaScript Fetch, Axios, Python, Go, PHP, and Rust',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 80,
    slug: 'rsa-key-pair-generator',
    name: 'RSA & ECDSA Key Pair Generator',
    shortDescription: 'Generate RSA and ECDSA public/private key pairs in PEM format securely in browser',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 81,
    slug: 'svg-optimizer',
    name: 'SVG Optimizer & Cleaner',
    shortDescription: 'Minify SVG code, remove editor metadata, clean paths, and inspect byte savings',
    categorySlug: 'formatters',
    categoryName: 'Code Formatters',
    isFeatured: true,
  },
  {
    id: 82,
    slug: 'html-table-to-json',
    name: 'HTML Table to JSON Converter',
    shortDescription: 'Extract and parse HTML table markup into structured JSON objects or arrays',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 83,
    slug: 'favicon-generator',
    name: 'Favicon & App Icon Generator',
    shortDescription: 'Generate 16x16, 32x32, Apple Touch icons, web manifest, and HTML link tags',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 84,
    slug: 'gitignore-generator',
    name: '.gitignore Generator',
    shortDescription: 'Generate customized .gitignore files for Node, Python, Java, Go, Rust, macOS, and IDEs',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 85,
    slug: 'htpasswd-generator',
    name: '.htpasswd Generator',
    shortDescription: 'Generate Bcrypt, MD5, and SHA-1 password hashes for Apache and Nginx HTTP Basic Auth',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 86,
    slug: 'dockerfile-generator',
    name: 'Dockerfile Generator',
    shortDescription: 'Generate production-ready multi-stage Dockerfiles for Node, Python, Go, Rust, and Nginx',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 87,
    slug: 'css-glassmorphism',
    name: 'CSS Glassmorphism Generator',
    shortDescription: 'Design modern frosted glass UI cards with real-time blur, opacity, and Tailwind CSS',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 88,
    slug: 'css-grid-generator',
    name: 'CSS Grid Layout Generator',
    shortDescription: 'Create custom CSS Grid layouts with column/row spans, gaps, and interactive preview',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 89,
    slug: 'css-blob-generator',
    name: 'CSS & SVG Blob Generator',
    shortDescription: 'Generate smooth organic blob shapes using fancy CSS border-radius and SVG paths',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 90,
    slug: 'robots-txt-generator',
    name: 'robots.txt Generator & Tester',
    shortDescription: 'Create SEO-optimized robots.txt files with custom user-agents, disallow rules, and sitemaps',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 91,
    slug: 'sitemap-generator',
    name: 'XML Sitemap Generator',
    shortDescription: 'Generate valid sitemap.xml files with lastmod, changefreq, and priority tags from URL lists',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 92,
    slug: 'sql-to-json',
    name: 'SQL to JSON Converter',
    shortDescription: 'Convert SQL INSERT statements and table dumps into structured JSON arrays and objects',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 93,
    slug: 'totp-generator',
    name: '2FA / TOTP Authenticator Generator',
    shortDescription: 'Generate RFC 6238 TOTP security codes, base32 secrets, and otpauth:// QR URIs',
    categorySlug: 'crypto',
    categoryName: 'Cryptography',
    isFeatured: true,
  },
  {
    id: 94,
    slug: 'markdown-table-generator',
    name: 'Markdown Table Generator',
    shortDescription: 'Create, edit, and format GitHub Markdown tables with an interactive spreadsheet editor',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
  {
    id: 95,
    slug: 'key-code-info',
    name: 'JavaScript Keycode Info',
    shortDescription: 'Inspect keyboard event.key, code, which, and keyCode values with live keypress listener',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 96,
    slug: 'aspect-ratio-calculator',
    name: 'Aspect Ratio Calculator',
    shortDescription: 'Calculate 16:9, 4:3, 21:9 image and video aspect ratios with proportional resizing',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 97,
    slug: 'base64-to-image',
    name: 'Base64 to Image Decoder',
    shortDescription: 'Decode Base64 strings and Data URIs back into PNG, JPG, WebP, and SVG image files',
    categorySlug: 'encoding',
    categoryName: 'Encoder Online',
    isFeatured: true,
  },
  {
    id: 98,
    slug: 'html-to-markdown',
    name: 'HTML to Markdown Converter',
    shortDescription: 'Convert HTML markup, headings, links, blockquotes, and lists into clean Markdown',
    categorySlug: 'converters',
    categoryName: 'Converters',
    isFeatured: true,
  },
  {
    id: 99,
    slug: 'css-triangle-generator',
    name: 'CSS Triangle Generator',
    shortDescription: 'Generate pure CSS border triangles and tooltips pointing in any direction',
    categorySlug: 'utilities',
    categoryName: 'Developer Utilities',
    isFeatured: true,
  },
  {
    id: 100,
    slug: 'svg-placeholder-generator',
    name: 'SVG Placeholder Generator',
    shortDescription: 'Generate custom SVG and Data URI image placeholders with dimensions and custom text',
    categorySlug: 'generators',
    categoryName: 'Generators',
    isFeatured: true,
  },
] as const satisfies readonly Tool[];

export type ToolSlug = (typeof toolCatalog)[number]['slug'];

const categoryBySlug = new Map<string, Category>(
  categoryCatalog.map((category) => [category.slug, category]),
);
const toolBySlug = new Map<string, Tool>(toolCatalog.map((tool) => [tool.slug, tool]));

export function findCatalogTool(slug: string): Tool | undefined {
  return toolBySlug.get(slug);
}

export function isToolSlug(slug: string): slug is ToolSlug {
  return toolBySlug.has(slug);
}

const curatedRelatedToolSlugs: Record<string, string[]> = {
  'json-formatter': ['json-validator', 'json-to-typescript', 'json-csv'],
  'json-to-typescript': ['json-to-zod', 'json-to-models', 'json-schema-validator'],
  'json-csv': ['csv-to-markdown', 'sql-formatter', 'html-table-to-json'],
  'sql-formatter': ['json-to-sql', 'json-formatter', 'html-formatter'],
  'jwt-decoder': ['certificate-decoder', 'hmac-generator', 'base64'],
  'base64': ['base64-to-image', 'image-to-base64', 'jwt-decoder'],
  'image-to-base64': ['base64-to-image', 'favicon-generator', 'base64'],
  'hex-encoder': ['base64', 'binary-encoder', 'number-base-converter'],
  'binary-encoder': ['hex-encoder', 'base64', 'number-base-converter'],
  'number-base-converter': ['hex-encoder', 'binary-encoder', 'roman-numeral-converter'],
  'regex-tester': ['regex-escape', 'text-diff', 'case-converter'],
  'regex-escape': ['regex-tester', 'text-diff', 'case-converter'],
  'uuid-generator': ['password-generator', 'qr-code', 'slug-generator'],
  'password-generator': ['rsa-key-pair-generator', 'bcrypt-generator', 'bip39-generator'],
  'slug-generator': ['gitignore-generator', 'uuid-generator', 'meta-tags'],
  'qr-code': ['totp-generator', 'url-encoder', 'uuid-generator'],
  'lorem-ipsum': ['mock-data-generator', 'slug-generator', 'uuid-generator'],
  'word-counter': ['case-converter', 'markdown-preview', 'lorem-ipsum'],
  'markdown-preview': ['html-to-markdown', 'markdown-table-generator', 'word-counter'],
  'sort-lines': ['remove-duplicates', 'text-diff', 'word-counter'],
  'remove-duplicates': ['sort-lines', 'markdown-preview', 'text-diff'],
  'text-diff': ['sort-lines', 'remove-duplicates', 'lorem-ipsum'],
  'url-encoder': ['url-parser', 'qr-code', 'query-string-parser'],
  'meta-tags': ['robots-txt-generator', 'sitemap-generator', 'favicon-generator'],
  'md5-hash': ['sha256-hash', 'sha512-hash', 'hmac-generator'],
  'sha256-hash': ['sha512-hash', 'certificate-decoder', 'pkce-generator'],
  'sha512-hash': ['sha256-hash', 'hmac-generator', 'md5-hash'],
  'hmac-generator': ['bcrypt-generator', 'pkce-generator', 'sha256-hash'],
  'url-parser': ['query-string-parser', 'user-agent-parser', 'url-encoder'],
  'query-string-parser': ['url-parser', 'url-encoder', 'user-agent-parser'],
  'http-headers-parser': ['curl-to-code', 'dmarc-generator', 'user-agent-parser'],
  'user-agent-parser': ['key-code-info', 'cidr-calculator', 'url-parser'],
  'http-status-codes': ['http-headers-parser', 'cache-control', 'curl-to-fetch'],
  'pkce-generator': ['sha256-hash', 'hmac-generator', 'bip39-generator'],
  'cidr-calculator': ['url-parser', 'http-headers-parser', 'http-status-codes'],
  'json-pointer': ['json-diff-patch', 'jsonpath-tester', 'json-formatter'],
  'jsonpath-tester': ['json-diff-patch', 'json-pointer', 'json-schema-validator'],
  'chmod-calculator': ['key-code-info', 'timestamp-converter', 'cron-generator'],
  'cache-control': ['http-headers-parser', 'csp-builder', 'curl-to-fetch'],
  'csp-builder': ['cache-control', 'dmarc-generator', 'curl-to-fetch'],
  'curl-to-fetch': ['curl-to-code', 'openapi-validator', 'http-status-codes'],
  'yaml-json': ['env-to-json', 'json-formatter', 'json-validator'],
  'env-to-json': ['yaml-json', 'docker-run-to-compose', 'json-formatter'],
  'json-to-zod': ['json-to-typescript', 'json-to-models', 'json-schema-validator'],
  'bcrypt-generator': ['htpasswd-generator', 'md5-hash', 'password-generator'],
  'json-diff-patch': ['json-pointer', 'jsonpath-tester', 'json-validator'],
  'color-contrast-checker': ['color-converter', 'css-box-shadow', 'css-gradient'],
  'certificate-decoder': ['rsa-key-pair-generator', 'jwt-decoder', 'sha256-hash'],
  'openapi-validator': ['curl-to-code', 'curl-to-fetch', 'http-headers-parser'],
  'color-converter': ['color-contrast-checker', 'css-gradient', 'css-clamp'],
  'css-gradient': ['color-contrast-checker', 'css-clamp', 'meta-tags'],
  'html-formatter': ['xml-formatter', 'html-to-markdown', 'html-minifier'],
  'html-minifier': ['html-formatter', 'js-minifier', 'css-minifier'],
  'xml-formatter': ['html-formatter', 'html-minifier', 'svg-minifier'],
  'css-minifier': ['js-minifier', 'html-minifier', 'svg-minifier'],
  'js-minifier': ['html-minifier', 'css-minifier', 'svg-minifier'],
  'unicode-escape': ['html-entity', 'json-string-escape', 'base64'],
  'json-string-escape': ['unicode-escape', 'html-entity', 'json-formatter'],
  'case-converter': ['regex-tester', 'regex-escape', 'word-counter'],
  'html-entity': ['unicode-escape', 'xml-formatter', 'json-string-escape'],
  'svg-to-jsx': ['svg-optimizer', 'svg-minifier', 'html-entity'],
  'svg-minifier': ['svg-optimizer', 'svg-to-jsx', 'html-minifier'],
  'css-clamp': ['css-grid-generator', 'px-to-rem', 'css-box-shadow'],
  'css-box-shadow': ['css-glassmorphism', 'px-to-rem', 'color-converter'],
  'docker-run-to-compose': ['dockerfile-generator', 'cron-generator', 'env-to-json'],
  'cron-generator': ['cron-parser', 'chmod-calculator', 'docker-run-to-compose'],
  'cron-parser': ['cron-generator', 'timestamp-converter', 'chmod-calculator'],
  'timestamp-converter': ['cron-parser', 'cron-generator', 'roman-numeral-converter'],
  'json-to-sql': ['sql-to-json', 'sql-formatter', 'json-csv'],
  'bip39-generator': ['totp-generator', 'password-generator', 'sha256-hash'],
  'dmarc-generator': ['robots-txt-generator', 'certificate-decoder', 'csp-builder'],
  'json-to-models': ['mock-data-generator', 'sql-formatter', 'json-to-sql'],
  'px-to-rem': ['aspect-ratio-calculator', 'css-grid-generator', 'css-clamp'],
  'mock-data-generator': ['uuid-generator', 'json-formatter', 'json-to-models'],
  'csv-to-markdown': ['markdown-table-generator', 'html-to-markdown', 'html-table-to-json'],
  'curl-to-code': ['curl-to-fetch', 'openapi-validator', 'json-to-models'],
  'rsa-key-pair-generator': ['certificate-decoder', 'hmac-generator', 'sha256-hash'],
  'svg-optimizer': ['svg-placeholder-generator', 'svg-to-jsx', 'svg-minifier'],
  'html-table-to-json': ['markdown-table-generator', 'sql-to-json', 'csv-to-markdown'],
  'favicon-generator': ['svg-placeholder-generator', 'base64-to-image', 'image-to-base64'],
  'gitignore-generator': ['dockerfile-generator', 'slug-generator', 'uuid-generator'],
  'htpasswd-generator': ['bcrypt-generator', 'md5-hash', 'totp-generator'],
  'dockerfile-generator': ['docker-run-to-compose', 'gitignore-generator', 'env-to-json'],
  'css-glassmorphism': ['css-triangle-generator', 'css-blob-generator', 'css-gradient'],
  'css-grid-generator': ['css-clamp', 'css-glassmorphism', 'px-to-rem'],
  'css-blob-generator': ['css-triangle-generator', 'css-glassmorphism', 'svg-optimizer'],
  'robots-txt-generator': ['sitemap-generator', 'meta-tags', 'dmarc-generator'],
  'sitemap-generator': ['robots-txt-generator', 'url-parser', 'meta-tags'],
  'sql-to-json': ['json-to-sql', 'sql-formatter', 'html-table-to-json'],
  'totp-generator': ['htpasswd-generator', 'qr-code', 'bip39-generator'],
  'markdown-table-generator': ['csv-to-markdown', 'html-table-to-json', 'html-to-markdown'],
  'key-code-info': ['cidr-calculator', 'user-agent-parser', 'chmod-calculator'],
  'aspect-ratio-calculator': ['px-to-rem', 'css-clamp', 'svg-placeholder-generator'],
  'base64-to-image': ['image-to-base64', 'base64', 'favicon-generator'],
  'html-to-markdown': ['markdown-preview', 'markdown-table-generator', 'html-formatter'],
  'css-triangle-generator': ['css-glassmorphism', 'css-blob-generator', 'css-box-shadow'],
  'svg-placeholder-generator': ['aspect-ratio-calculator', 'favicon-generator', 'svg-optimizer'],
};

function relatedToolsFor(tool: Tool, count: number = 3): Tool[] {
  const categoryTools = toolCatalog.filter(
    (candidate) => candidate.categorySlug === tool.categorySlug,
  );
  const categoryIndex = categoryTools.findIndex((candidate) => candidate.slug === tool.slug);
  const categoryRing = categoryTools
    .slice(categoryIndex + 1)
    .concat(categoryTools.slice(0, categoryIndex));
  const globalIndex = toolCatalog.findIndex((candidate) => candidate.slug === tool.slug);
  const globalRing = toolCatalog.slice(globalIndex + 1).concat(toolCatalog.slice(0, globalIndex));
  const candidates = [
    ...(curatedRelatedToolSlugs[tool.slug] || [])
      .map((slug) => toolCatalog.find((candidate) => candidate.slug === slug))
      .filter((candidate): candidate is (typeof toolCatalog)[number] => candidate !== undefined),
    ...categoryRing,
    ...globalRing,
  ];

  const unique = new Map<string, Tool>();
  for (const candidate of candidates) {
    if (candidate.slug !== tool.slug && !unique.has(candidate.slug)) {
      unique.set(candidate.slug, candidate);
    }
  }

  return [...unique.values()].slice(0, count);
}

function asDetail(tool: Tool): ToolDetail {
  return {
    ...tool,
    longDescription: tool.shortDescription,
    keywords: tool.name.split(' '),
    seo: {
      title: `${tool.name} | DevsTools`,
      metaDescription: tool.shortDescription,
    },
    faqs: [],
    relatedTools: relatedToolsFor(tool),
  };
}

// Categories API (static)
export async function getCategories(): Promise<Category[]> {
  return [...categoryCatalog];
}

export async function getCategoryBySlug(slug: string): Promise<Category | null> {
  return categoryBySlug.get(slug) || null;
}

// Tools API (static)
export async function getTools(): Promise<Tool[]> {
  return [...toolCatalog];
}

export async function getToolBySlug(slug: string): Promise<ToolDetail | null> {
  const tool = findCatalogTool(slug);
  return tool ? asDetail(tool) : null;
}

export async function getFeaturedTools(count: number = 10): Promise<Tool[]> {
  return toolCatalog.filter((t) => t.isFeatured).slice(0, count);
}

export async function getPopularTools(count: number = toolCatalog.length): Promise<Tool[]> {
  return toolCatalog.slice(0, count);
}
