export function convertJsonToGoStruct(jsonStr: string, rootName = 'AutoGenerated'): string {
  const parsed = JSON.parse(jsonStr);
  const structs: string[] = [];

  function toPascalCase(str: string): string {
    return str.replace(/(^|[^a-zA-Z0-9])([a-zA-Z0-9])/g, (_, __, c) => c.toUpperCase());
  }

  function generateStruct(name: string, obj: Record<string, any>) {
    const fields: string[] = [];
    for (const [key, val] of Object.entries(obj)) {
      const fieldName = toPascalCase(key) || 'Field';
      let typeStr = 'interface{}';
      if (val === null) typeStr = 'interface{}';
      else if (typeof val === 'string') typeStr = 'string';
      else if (typeof val === 'number') typeStr = Number.isInteger(val) ? 'int' : 'float64';
      else if (typeof val === 'boolean') typeStr = 'bool';
      else if (Array.isArray(val)) {
        if (val.length > 0 && typeof val[0] === 'object' && val[0] !== null) {
          const sub = name + toPascalCase(key);
          generateStruct(sub, val[0]);
          typeStr = '[]' + sub;
        } else if (val.length > 0) {
          const inner = typeof val[0] === 'string' ? 'string' : typeof val[0] === 'number' ? (Number.isInteger(val[0]) ? 'int' : 'float64') : 'bool';
          typeStr = '[]' + inner;
        } else {
          typeStr = '[]interface{}';
        }
      } else if (typeof val === 'object') {
        const sub = name + toPascalCase(key);
        generateStruct(sub, val);
        typeStr = sub;
      }
      fields.push('\t' + fieldName + ' ' + typeStr + ' ' + '`' + 'json:"' + key + '"' + '`');
    }
    structs.push('type ' + name + ' struct {\n' + fields.join('\n') + '\n}');
  }

  if (Array.isArray(parsed)) {
    if (parsed.length > 0 && typeof parsed[0] === 'object') {
      generateStruct(rootName + 'Item', parsed[0]);
      return 'package main\n\ntype ' + rootName + ' []' + rootName + 'Item\n\n' + structs.join('\n\n');
    }
    return 'package main\n\ntype ' + rootName + ' []interface{}';
  }
  generateStruct(rootName, parsed);
  return 'package main\n\n' + structs.join('\n\n');
}
