export function jsonToGoStruct(jsonStr: string, structName: string = 'AutoGenerated'): string {
  try {
    const obj = JSON.parse(jsonStr);
    const lines = [`type ${structName} struct {`];

    for (const [k, v] of Object.entries(obj)) {
      const goField = k.charAt(0).toUpperCase() + k.slice(1);
      let goType = 'interface{}';
      if (typeof v === 'string') goType = 'string';
      else if (typeof v === 'number') goType = Number.isInteger(v) ? 'int' : 'float64';
      else if (typeof v === 'boolean') goType = 'bool';
      else if (Array.isArray(v)) goType = '[]interface{}';
      else if (typeof v === 'object' && v !== null) goType = 'map[string]interface{}';

      lines.push(`\t${goField} ${goType} ` + '`json:"' + k + '"`');
    }

    lines.push('}');
    return lines.join('\n');
  } catch {
    return '// Error: Invalid JSON input';
  }
}
