export function convertOpenApiToTypeScript(schemaInput: string): string {
  try {
    let schema: any;
    try {
      schema = JSON.parse(schemaInput);
    } catch {
      return '// Error: Please provide valid OpenAPI / Swagger JSON content.';
    }

    const lines: string[] = [
      '/**',
      ` * ${schema.info?.title || 'API Client'}`,
      ` * Version: ${schema.info?.version || '1.0.0'}`,
      ' * Generated by DevsTools Swagger to TypeScript Client Generator',
      ' */',
      '',
    ];

    const definitions = schema.definitions || schema.components?.schemas || {};
    for (const [name, def] of Object.entries<any>(definitions)) {
      lines.push(`export interface ${name} {`);
      const properties = def.properties || {};
      const required = new Set(def.required || []);
      for (const [propName, propDef] of Object.entries<any>(properties)) {
        const isReq = required.has(propName);
        const tsType = mapOpenApiTypeToTs(propDef);
        lines.push(`  ${propName}${isReq ? '' : '?'}: ${tsType};`);
      }
      lines.push('}');
      lines.push('');
    }

    if (schema.paths) {
      lines.push('export class ApiClient {');
      lines.push('  constructor(private baseUrl: string = "") {}');
      lines.push('');
      for (const [path, methods] of Object.entries<any>(schema.paths)) {
        for (const [method, op] of Object.entries<any>(methods)) {
          if (['get', 'post', 'put', 'delete', 'patch'].includes(method.toLowerCase())) {
            const opId = op.operationId || `${method}_${path.replace(/[^a-zA-Z0-9]/g, '_')}`;
            lines.push(`  async ${opId}(options?: RequestInit): Promise<any> {`);
            lines.push(`    const res = await fetch(\`\${this.baseUrl}\${'${path}'}\`, { method: '${method.toUpperCase()}', ...options });`);
            lines.push('    if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);');
            lines.push('    return res.json();');
            lines.push('  }');
            lines.push('');
          }
        }
      }
      lines.push('}');
    }

    return lines.join('\n');
  } catch (err: any) {
    return `// Generation error: ${err.message}`;
  }
}

function mapOpenApiTypeToTs(prop: any): string {
  if (!prop) return 'any';
  if (prop.$ref) return prop.$ref.split('/').pop() || 'any';
  if (prop.type === 'string') return prop.enum ? prop.enum.map((e: any) => `'${e}'`).join(' | ') : 'string';
  if (prop.type === 'integer' || prop.type === 'number') return 'number';
  if (prop.type === 'boolean') return 'boolean';
  if (prop.type === 'array') return `${mapOpenApiTypeToTs(prop.items)}[]`;
  if (prop.type === 'object') return 'Record<string, any>';
  return 'any';
}
